package routers

// Replays testdata/overview-pool-cases.json — generated by driving the LIVE
// src/overviewSessions.js — into the ported decisions.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"testing"
)

type poolCase struct {
	Name       string              `json:"name"`
	Steps      [][]json.RawMessage `json:"steps"`
	Trace      [][]json.RawMessage `json:"trace"`
	Collectors [][]any             `json:"collectors"`
}

// The live pool runs exactly three collectors per session, so one "start"
// decision here is three entries in its log. Named rather than written as a
// bare 3 at each use — if a fourth is ever added there, this is the line that
// has to change and the test that says so.
const collectorsPerSession = 3

func TestOverviewPoolMatchesTheLiveModule(t *testing.T) {
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "overview-pool-cases.json"))
	if err != nil {
		t.Fatalf("no corpus — run: node tools/overview-pool-cases.js: %v", err)
	}
	var payload struct {
		Cases []poolCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		t.Fatal(err)
	}
	if len(payload.Cases) == 0 {
		t.Fatal("the corpus is empty")
	}

	totalStarts := 0
	for _, c := range payload.Cases {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			tracked := map[string]bool{}
			sessions := map[string]*OverviewSession{}
			// DESTROYED SESSIONS STAY REACHABLE, because they do in the live
			// pool: `_stopSession` sets a flag and the ROS client can still
			// deliver an in-flight `connected` afterwards. An earlier version of
			// this harness deleted them, so a late connect found nothing and the
			// mutation removing the `destroyed` guard SURVIVED — the test was
			// bypassing the very guard it was written for.
			torn := map[string]*OverviewSession{}
			suspended := false
			starts, stops := 0, 0
			traceAt := 0

			str := func(raw json.RawMessage) string {
				var s string
				if err := json.Unmarshal(raw, &s); err != nil {
					t.Fatal(err)
				}
				return s
			}

			for _, step := range c.Steps {
				op := str(step[0])
				switch op {
				case "sync":
					var all []string
					var excl []string
					if err := json.Unmarshal(step[1], &all); err != nil {
						t.Fatal(err)
					}
					if len(step) > 2 {
						if err := json.Unmarshal(step[2], &excl); err != nil {
							t.Fatal(err)
						}
					}
					exclSet := map[string]bool{}
					for _, e := range excl {
						exclSet[e] = true
					}
					act := SyncPool(all, exclSet, tracked)
					for _, id := range act.Stop {
						// A teardown stops all three whatever their state — the
						// live `_stopSession` does not check.
						sessions[id].Destroy()
						torn[id] = sessions[id]
						delete(sessions, id)
						delete(tracked, id)
						stops += collectorsPerSession
					}
					for _, id := range act.Start {
						// A BUILD FOR A ROUTER ALREADY TRACKED IS A DEFECT, not
						// a no-op: the live pool would hold two sessions and two
						// connections to one router. The map here would silently
						// absorb it, so it is asserted — a mutation dropping the
						// `tracked[id]` skip survived until this line existed.
						if tracked[id] {
							t.Fatalf("SyncPool asked to start %q, which is already tracked — "+
								"that is a second connection to one router", id)
						}
						s := &OverviewSession{}
						if suspended {
							s.Suspend()
						}
						sessions[id] = s
						tracked[id] = true
					}
					// Membership after the sync, against what the live pool holds.
					var got []string
					for id := range tracked {
						got = append(got, id)
					}
					sort.Strings(got)
					var want []string
					if err := json.Unmarshal(c.Trace[traceAt][1], &want); err != nil {
						t.Fatal(err)
					}
					if len(got) != len(want) {
						t.Fatalf("after sync: tracking %v, live tracks %v", got, want)
					}
					for i := range got {
						if got[i] != want[i] {
							t.Fatalf("after sync: tracking %v, live tracks %v", got, want)
						}
					}

				case "connect", "close", "error":
					id := str(step[1])
					s := sessions[id]
					if s == nil {
						// A late event on a torn-down session: the live pool
						// still delivers it, and the `destroyed` guard is what
						// stops it restarting anything.
						s = torn[id]
					}
					if s != nil {
						switch op {
						case "connect":
							if s.OnConnected() {
								starts += collectorsPerSession
							}
						case "close":
							s.OnClosed()
						case "error":
							// The generator's classifier calls exactly one
							// message "known"; everything else is unclassified.
							msg := ""
							if len(step) > 2 {
								msg = str(step[2])
							}
							if msg == "known" {
								s.OnError("Authentication failed", true)
							} else {
								s.OnError(msg, false)
							}
						}
					}
					// The live summary is absent for a torn-down router; so is
					// our session. That the two agree about ABSENCE is part of
					// the contract — a pool still holding a removed router
					// would keep polling it.
					var want []any
					if err := json.Unmarshal(c.Trace[traceAt][2], &want); err != nil {
						t.Fatal(err)
					}
					_, isTorn := torn[id]
					if want == nil {
						// The live pool has no SUMMARY for this router, which
						// means it was torn down. Ours must agree that it is not
						// tracked — a session still in `sessions` here would be
						// one the pool kept polling.
						if !isTorn && s != nil {
							t.Fatalf("%s %s: still tracked, live has no summary", op, id)
						}
						break
					}
					if s == nil {
						t.Fatalf("%s %s: no session here, live has %v", op, id, want)
					}
					if s.Connected != want[0].(bool) {
						t.Errorf("%s %s: connected=%v, live=%v", op, id, s.Connected, want[0])
					}
					wantErr := ""
					if want[1] != nil {
						wantErr = want[1].(string)
					}
					if s.LastError != wantErr {
						t.Errorf("%s %s: lastError=%q, live=%q", op, id, s.LastError, wantErr)
					}

				case "suspend":
					suspended = true
					for _, s := range sessions {
						s.Suspend()
						stops += collectorsPerSession
					}
				case "resume":
					suspended = false
					for _, s := range sessions {
						if s.Resume() {
							starts += collectorsPerSession
						}
					}
				default:
					t.Fatalf("unknown step %q", op)
				}
				traceAt++
			}

			liveStarts, liveStops := 0, 0
			for _, e := range c.Collectors {
				if e[2] == "start" {
					liveStarts++
				} else {
					liveStops++
				}
			}
			if starts != liveStarts {
				t.Errorf("started %d collectors, live started %d", starts, liveStarts)
			}
			if stops != liveStops {
				t.Errorf("stopped %d collectors, live stopped %d", stops, liveStops)
			}
			totalStarts += starts
		})
	}
	if totalStarts == 0 {
		t.Fatal("no case started a collector — this suite cannot see a pool that never runs")
	}
	t.Logf("%d collector starts compared", totalStarts)
}
