package notify

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The admin test-notification merge, against the corpus generated by RUNNING the
// live expression (the test-notif corpus).
//
// The corpus records only what each case CHANGED, so the expectation reads as
// the case's intent rather than as a copy of the whole settings map. This
// rebuilds the full expected map by applying those changes onto the stored one,
// and then compares every key — including the ones nothing should have touched,
// because a merge that dropped an unrelated setting would otherwise pass.

type adminMergeCorpus struct {
	Stored map[string]any `json:"stored"`
	Cases  []struct {
		Why     string         `json:"why"`
		Body    map[string]any `json:"body"`
		Stored  map[string]any `json:"stored"`
		Changed map[string]any `json:"changed"`
	} `json:"cases"`
}

func TestTheAdminTestMergeMatchesTheLiveRoute(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "..", "testdata", "test-notif-cases.json"))
	if err != nil {
		t.Fatalf("no corpus — run: node tools/test-notif-cases.js: %v", err)
	}
	var c adminMergeCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatal(err)
	}
	if len(c.Cases) == 0 {
		t.Fatal("the corpus is empty")
	}

	// BELIEVABILITY, in both directions: some cases must change something and
	// some must change nothing, or a merge that ignored the body entirely (or
	// one that overwrote everything) would pass the whole suite.
	changing, inert := 0, 0
	for _, k := range c.Cases {
		if len(k.Changed) > 0 {
			changing++
		} else {
			inert++
		}
	}
	if changing < 10 || inert < 2 {
		t.Fatalf("%d changing and %d inert cases — the corpus does not separate them",
			changing, inert)
	}

	for _, k := range c.Cases {
		t.Run(k.Why, func(t *testing.T) {
			stored := c.Stored
			if k.Stored != nil {
				stored = k.Stored
			}
			want := Settings{}
			for key, v := range stored {
				want[key] = v
			}
			for key, v := range k.Changed {
				want[key] = v
			}

			got := MergeForAdminTest(k.Body, Settings(stored))

			if len(got) != len(want) {
				t.Errorf("%d keys, want %d — the merge added or dropped one", len(got), len(want))
			}
			for key, w := range want {
				g, ok := got[key]
				if !ok {
					t.Errorf("%s is missing", key)
					continue
				}
				// JSON numbers arrive as float64 on both sides, so a direct
				// comparison is right for ports as well as strings and bools.
				if !sameJSON(g, w) {
					t.Errorf("%s = %#v, live = %#v", key, g, w)
				}
			}
		})
	}
}

func sameJSON(a, b any) bool {
	x, _ := json.Marshal(a)
	y, _ := json.Marshal(b)
	return string(x) == string(y)
}

// THE STORED MAP MUST NOT BE MUTATED. The route merges over the install's real
// settings, and a merge that wrote into them would leave a credential typed for
// one test in place for every later send — including the alerter's.
func TestTheAdminTestMergeDoesNotTouchTheStoredSettings(t *testing.T) {
	stored := Settings{"telegramBotToken": "stored", "smtpPort": float64(25)}
	before, _ := json.Marshal(stored)

	got := MergeForAdminTest(map[string]any{
		"botToken": "typed", "smtpPort": float64(465),
	}, stored)

	after, _ := json.Marshal(stored)
	if string(before) != string(after) {
		t.Errorf("the stored settings changed: %s -> %s", before, after)
	}
	if got["telegramBotToken"] != "typed" {
		t.Errorf("the merged copy did not take the typed token: %#v", got["telegramBotToken"])
	}
}
