package topology

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The corpus is generated by RUNNING `src/topologyLayout.js`, so `want` is the
// live module's own answer — including the rounding, which is the half of this
// nobody would get right by reading.
type layoutCase struct {
	Name  string           `json:"name"`
	Input string           `json:"input"`
	Want  map[string]Point `json:"want"`
}

func load(t *testing.T) (cases []layoutCase, rids []struct {
	RID string `json:"rid"`
	OK  bool   `json:"ok"`
}, limits struct {
	MaxNodes   int `json:"maxNodes"`
	CoordLimit int `json:"coordLimit"`
},
) {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "topology-layout-cases.json"))
	if err != nil {
		t.Fatalf("corpus: %v (regenerate with tools/topology-layout-cases.js)", err)
	}
	var doc struct {
		MaxNodes   int          `json:"maxNodes"`
		CoordLimit int          `json:"coordLimit"`
		Cases      []layoutCase `json:"cases"`
		RouterIDs  []struct {
			RID string `json:"rid"`
			OK  bool   `json:"ok"`
		} `json:"routerIDs"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Cases) < 20 {
		t.Fatalf("the corpus holds %d cases — it is not the generated one", len(doc.Cases))
	}
	limits.MaxNodes, limits.CoordLimit = doc.MaxNodes, doc.CoordLimit
	return doc.Cases, doc.RouterIDs, limits
}

func TestCleanPositionsMatchesTheLiveModule(t *testing.T) {
	cases, _, _ := load(t)
	for _, c := range cases {
		t.Run(c.Name, func(t *testing.T) {
			got, ok := CleanPositions(json.RawMessage(c.Input))

			// `want: null` is a REFUSAL, which the caller must turn into a 400.
			if c.Want == nil {
				if ok {
					t.Fatalf("accepted %s and returned %v; the live module refuses it", c.Input, got)
				}
				return
			}
			if !ok {
				t.Fatalf("refused %s; the live module accepts it as %v", c.Input, c.Want)
			}
			if len(got) != len(c.Want) {
				t.Fatalf("got %d entries, live has %d (%v vs %v)", len(got), len(c.Want), got, c.Want)
			}
			for k, want := range c.Want {
				g, present := got[k]
				if !present {
					t.Errorf("key %q missing", k)
					continue
				}
				// Compared as MARSHALLED JSON: -0 and 0 are equal as float64 but
				// are different bytes on disk, and this file is read back by the
				// Node app.
				a, _ := json.Marshal(g)
				b, _ := json.Marshal(want)
				if string(a) != string(b) {
					t.Errorf("key %q: got %s, live says %s", k, a, b)
				}
			}
		})
	}
}

// THE RULE THAT MATTERS MOST: one bad key refuses the WHOLE map. A port that
// skipped the entry would persist a partial layout and report success.
func TestOneBadKeyRefusesTheWholeMap(t *testing.T) {
	in := `{"a:1":{"x":1,"y":1},"../etc":{"x":2,"y":2}}`
	if got, ok := CleanPositions(json.RawMessage(in)); ok {
		t.Errorf("accepted a map containing a traversal key and returned %v — the good entry "+
			"must not survive alone", got)
	}
}

func TestRouterIDValidation(t *testing.T) {
	_, rids, _ := load(t)
	for _, r := range rids {
		if got := IsValidRouterID(r.RID); got != r.OK {
			t.Errorf("IsValidRouterID(%q) = %v, live says %v", r.RID, got, r.OK)
		}
	}
}

// The limits are the live module's, not numbers chosen here.
func TestLimitsMatchTheLiveModule(t *testing.T) {
	_, _, lim := load(t)
	if MaxNodes != lim.MaxNodes {
		t.Errorf("MaxNodes = %d, live says %d", MaxNodes, lim.MaxNodes)
	}
	if CoordLimit != lim.CoordLimit {
		t.Errorf("CoordLimit = %d, live says %d", CoordLimit, lim.CoordLimit)
	}
}

// An EMPTY map is accepted and is not a refusal — the operator cleared every
// node, which is a legitimate save.
func TestAnEmptyMapIsAccepted(t *testing.T) {
	got, ok := CleanPositions(json.RawMessage(`{}`))
	if !ok {
		t.Fatal("an empty map was refused")
	}
	if len(got) != 0 {
		t.Errorf("got %v, want an empty map", got)
	}
}
