package guard

// Replays testdata/wan-default-cases.json, generated by LIFTING the
// `activeDefaultWan` block out of src/index.js and running it.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type wanDefaultCase struct {
	Name             string           `json:"name"`
	Routes           []map[string]any `json:"routes"`
	Rows             []map[string]any `json:"rows"`
	ActiveDefaultWan string           `json:"activeDefaultWan"`
}

// asRows converts the corpus rows to the map[string]string a RouterOS reply
// really is. It reports a non-string value rather than coercing one: see the
// skip in the test below.
func asRows(in []map[string]any) ([]map[string]string, bool) {
	out := make([]map[string]string, 0, len(in))
	for _, r := range in {
		m := map[string]string{}
		for k, v := range r {
			s, ok := v.(string)
			if !ok {
				return nil, false
			}
			m[k] = s
		}
		out = append(out, m)
	}
	return out, true
}

func TestActiveDefaultWanMatchesTheLiveBlock(t *testing.T) {
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "wan-default-cases.json"))
	if err != nil {
		t.Fatalf("no corpus — run: node tools/wan-default-cases.js: %v", err)
	}
	var payload struct {
		Cases []wanDefaultCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		t.Fatal(err)
	}
	if len(payload.Cases) == 0 {
		t.Fatal("the corpus is empty")
	}

	named, skipped := 0, 0
	for _, c := range payload.Cases {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			routes, ok1 := asRows(c.Routes)
			rows, ok2 := asRows(c.Rows)
			if !ok1 || !ok2 {
				// One corpus case gives `active` as a JSON boolean, to pin that
				// the live code compares against the STRING 'true' rather than
				// testing truthiness. The RouterOS wire protocol carries only
				// strings, so that value cannot reach this function — and
				// inventing a representation for it would be testing a shape the
				// protocol never produces. Skipped explicitly rather than
				// silently coerced, so the gap is visible in the run.
				skipped++
				t.Skip("a non-string field the RouterOS wire protocol cannot produce")
			}
			got := ActiveDefaultWan(routes, rows)
			if got != c.ActiveDefaultWan {
				t.Errorf("activeDefaultWan = %q, live = %q", got, c.ActiveDefaultWan)
			}
			if got != "" {
				named++
			}
		})
	}

	// The corpus must be able to tell the rule from its plausible twin. The
	// generator asserts this too; repeating it here means a corpus swapped for a
	// weaker one cannot turn this suite into a no-op.
	if named == 0 {
		t.Error("no case named a WAN — this suite cannot see a function that always returns unknown")
	}
	if named == len(payload.Cases)-skipped {
		t.Error("every case named a WAN — this suite cannot see the exactly-one rule")
	}
	t.Logf("%d cases named a WAN, %d skipped", named, skipped)
}
