package guard

// Replays testdata/wanguard-cases.json — generated by running the LIVE
// src/routeros/wanGuard.js — into the port.
//
// This guard WARNS rather than refusing, and FAILS OPEN, so its failure mode is
// silence: a port that returned `none` for everything would still let every
// action through and would only be noticed by an admin who cut their own
// management path. The corpus is built to make that impossible to pass — it
// mixes warn and none, and the generator refuses to write a corpus that is all
// of one or all of the other.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type wanCase struct {
	Name           string   `json:"name"`
	ConnectedCidrs []string `json:"connectedCidrs"`
	SelfAddresses  *struct {
		Addresses []string `json:"addresses"`
	} `json:"selfAddresses"`
	Path *struct {
		Resolved bool    `json:"resolved"`
		Local    bool    `json:"local"`
		Address  *string `json:"address"`
	} `json:"path"`
	Actions []struct {
		TargetWan        *string `json:"targetWan"`
		ActiveDefaultWan string  `json:"activeDefaultWan"`
		Verdict          struct {
			Level       string  `json:"level"`
			Code        *string `json:"code"`
			Fingerprint *string `json:"fingerprint"`
			Detail      *struct {
				Address string `json:"address"`
				Wan     string `json:"wan"`
				Certain bool   `json:"certain"`
			} `json:"detail"`
		} `json:"verdict"`
	} `json:"actions"`
}

func loadWanCases(t *testing.T) []wanCase {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "wanguard-cases.json"))
	if err != nil {
		t.Fatalf("no corpus — run: node tools/wanguard-cases.js: %v", err)
	}
	var payload struct {
		Cases []wanCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		t.Fatal(err)
	}
	if len(payload.Cases) == 0 {
		t.Fatal("the corpus is empty")
	}
	return payload.Cases
}

func TestWanGuardMatchesTheLiveModule(t *testing.T) {
	cases := loadWanCases(t)
	warned := 0
	for _, c := range cases {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			// A case with an explicitly null path pins the fail-open branch on
			// input the handler can really pass; every other case resolves its
			// path here, so the two functions are driven in sequence exactly as
			// the WAN handler drives them.
			var path *WanPath
			if c.SelfAddresses != nil || c.Path != nil {
				var addrs []string
				if c.SelfAddresses != nil {
					addrs = c.SelfAddresses.Addresses
				}
				got := ResolveWanPath(addrs, c.ConnectedCidrs)
				path = &got

				if c.Path == nil {
					path = nil
				} else {
					if got.Resolved != c.Path.Resolved || got.Local != c.Path.Local {
						t.Fatalf("path = {resolved:%v local:%v}, live = {resolved:%v local:%v}",
							got.Resolved, got.Local, c.Path.Resolved, c.Path.Local)
					}
					wantAddr := ""
					if c.Path.Address != nil {
						wantAddr = *c.Path.Address
					}
					if got.Address != wantAddr {
						t.Errorf("path address = %q, live = %q — the remote case reports the "+
							"FIRST OFF-SUBNET address, not the first address", got.Address, wantAddr)
					}
				}
			}

			for _, a := range c.Actions {
				target := ""
				if a.TargetWan != nil {
					target = *a.TargetWan
				}
				v := CheckLeaseAction(path, target, a.ActiveDefaultWan)
				w := a.Verdict
				if v.Level != w.Level {
					t.Errorf("target=%q default=%q: level = %q, live = %q",
						target, a.ActiveDefaultWan, v.Level, w.Level)
					continue
				}
				if w.Level != "warn" {
					// A `none` carries nothing else in the original: no code, no
					// detail, no fingerprint. A port that filled them in would
					// hand the browser something to acknowledge for an action
					// that was never gated.
					if v.Code != "" || v.Detail != nil || v.Fingerprint != "" {
						t.Errorf("target=%q: a `none` verdict carries code=%q detail=%v fingerprint=%q",
							target, v.Code, v.Detail, v.Fingerprint)
					}
					continue
				}
				warned++
				if w.Code == nil || v.Code != *w.Code {
					t.Errorf("target=%q: code = %q, live = %v", target, v.Code, w.Code)
				}
				if w.Fingerprint == nil || v.Fingerprint != *w.Fingerprint {
					t.Errorf("target=%q: fingerprint = %s, live = %v — the browser echoes this "+
						"back verbatim, so a byte of difference rejects every acknowledgement",
						target, v.Fingerprint, w.Fingerprint)
				}
				if w.Detail == nil {
					t.Fatalf("target=%q: live warned with no detail", target)
				}
				if v.Detail["address"] != w.Detail.Address {
					t.Errorf("target=%q: detail.address = %v, live = %q", target, v.Detail["address"], w.Detail.Address)
				}
				if v.Detail["wan"] != w.Detail.Wan {
					t.Errorf("target=%q: detail.wan = %v, live = %q", target, v.Detail["wan"], w.Detail.Wan)
				}
				if v.Detail["certain"] != w.Detail.Certain {
					t.Errorf("target=%q default=%q: detail.certain = %v, live = %v — false means "+
						"\"we could not identify the active default route\", and the UI words the "+
						"prompt differently", target, a.ActiveDefaultWan, v.Detail["certain"], w.Detail.Certain)
				}
			}
		})
	}
	// The corpus generator already refuses to write an all-none corpus; this is
	// The same check on the consuming side, so a corpus swapped for a weaker one
	// cannot quietly turn this suite into a no-op.
	if warned == 0 {
		t.Fatal("no case warned — this suite cannot tell a working guard from a silent one")
	}
	t.Logf("%d warning verdicts compared", warned)
}
