package server

import (
	"bytes"
	"encoding/json"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"mikrodash/internal/collection"
)

// The payload matches what the LIVE route computes.
//
// `testdata/collection-cases.json` carries `apiCollectors`, generated by running
// the live route's own filter-and-map over `collection.js`'s registry — so this
// compares against the original's expression rather than against a second
// reading of it.
func TestCollectorsPayloadMatchesTheLiveRoute(t *testing.T) {
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "collection-cases.json"))
	if err != nil {
		t.Fatalf("corpus: %v (regenerate with tools/collection-cases.js)", err)
	}
	var doc struct {
		APICollectors []collectorEntry `json:"apiCollectors"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.APICollectors) < 5 {
		t.Fatalf("the corpus holds %d entries — it is not the generated one",
			len(doc.APICollectors))
	}

	rec := httptest.NewRecorder()
	(&Server{}).collectorsGet(rec, httptest.NewRequest("GET", collectorsPath, nil))
	if rec.Code != 200 {
		t.Fatalf("status %d", rec.Code)
	}
	var got struct {
		Collectors []collectorEntry `json:"collectors"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &got); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got.Collectors, doc.APICollectors) {
		t.Errorf("payload differs\n  got  %+v\n  live %+v", got.Collectors, doc.APICollectors)
	}
}

// A PROTECTED COLLECTOR MUST NOT APPEAR. The dialog draws a checkbox per entry,
// and `resolveCollection` forces `enabled` true for anything not disableable —
// so offering one would give the operator a switch that does nothing.
func TestProtectedCollectorsAreNotOffered(t *testing.T) {
	rec := httptest.NewRecorder()
	(&Server{}).collectorsGet(rec, httptest.NewRequest("GET", collectorsPath, nil))
	var got struct {
		Collectors []collectorEntry `json:"collectors"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &got); err != nil {
		t.Fatal(err)
	}
	offered := map[string]bool{}
	for _, c := range got.Collectors {
		offered[c.Key] = true
	}
	for _, c := range collection.Collectors() {
		if !c.Disableable && offered[c.Key] {
			t.Errorf("%q is protected in the registry and was offered as a toggle", c.Key)
		}
	}
	// And the believability half: SOMETHING was offered, or the loop above is
	// checking an empty list.
	if len(got.Collectors) == 0 {
		t.Fatal("no collectors offered at all")
	}
}

// `requires` is ALWAYS an array, never null — the dialog iterates it without
// checking, and Go's nil slice marshals to `null`.
func TestRequiresIsNeverNull(t *testing.T) {
	rec := httptest.NewRecorder()
	(&Server{}).collectorsGet(rec, httptest.NewRequest("GET", collectorsPath, nil))
	if bytes.Contains(rec.Body.Bytes(), []byte(`"requires":null`)) {
		t.Error("a collector sent `requires: null`; the dialog iterates it without checking")
	}
}
