package history

// Replays testdata/connectivity-cases.json — generated by driving the LIVE
// src/alertSessions.js — into the ported state machine.
//
// The corpus is authoritative. Every expectation in it was produced by running
// the live module, so a disagreement here is this port being wrong until proven
// otherwise. That already paid off once during authoring: a scenario named
// "threshold 0, repeated closes do not double-record" was named from reading
// the live guard, and the corpus recorded two rows. The guard is on the ALERT,
// not on the row. The name was wrong, not the code.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type connCase struct {
	Name         string              `json:"name"`
	Note         string              `json:"note"`
	ThresholdSec int64               `json:"thresholdSec"`
	Steps        [][]json.RawMessage `json:"steps"`
	Rows         []struct {
		Connected bool   `json:"connected"`
		TsArg     *int64 `json:"tsArg"`
		RowTs     int64  `json:"rowTs"`
		AtClock   int64  `json:"atClock"`
	} `json:"rows"`
	StatusEmits []struct {
		Connected bool  `json:"connected"`
		AtClock   int64 `json:"atClock"`
	} `json:"statusEmits"`
}

func loadConnCases(t *testing.T) []connCase {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "connectivity-cases.json"))
	if err != nil {
		t.Fatalf("no corpus — run: node tools/connectivity-cases.js: %v", err)
	}
	var payload struct {
		Cases []connCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		t.Fatal(err)
	}
	if len(payload.Cases) == 0 {
		t.Fatal("the corpus is empty")
	}
	return payload.Cases
}

func TestConnectivityMatchesTheLiveStateMachine(t *testing.T) {
	cases := loadConnCases(t)
	for _, c := range cases {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			m := &Connectivity{RouterID: "r", ThreshMs: c.ThresholdSec * 1000}
			var now int64
			var got []Row
			var status []bool

			apply := func(e ConnEffect) {
				got = append(got, e.Rows...)
				status = append(status, e.Status...)
			}

			for _, step := range c.Steps {
				var op string
				if err := json.Unmarshal(step[0], &op); err != nil {
					t.Fatal(err)
				}
				switch op {
				case "connect":
					apply(m.Connected(now))
				case "close", "error":
					apply(m.Disconnected(now))
				case "advance":
					var ms int64
					if err := json.Unmarshal(step[1], &ms); err != nil {
						t.Fatal(err)
					}
					// Mirrors the generator's fake clock exactly: a due timer
					// fires AT its own moment mid-advance, and the clock then
					// lands on the target. Ticking only at the end of the
					// advance would still produce the right timestamp — the
					// row carries the OBSERVED moment either way — and that is
					// precisely why it must not be done that way here: it
					// would hide whether the port kept rule 2 or merely
					// happened to agree.
					target := now + ms
					if m.timerLive && m.timerAt <= target {
						now = m.timerAt
						apply(m.Tick(now))
					}
					now = target
				default:
					t.Fatalf("unknown step %q", op)
				}
			}
			compareRows(t, c, got, status)
		})
	}
}

func compareRows(t *testing.T, c connCase, got []Row, status []bool) {
	t.Helper()
	if len(got) != len(c.Rows) {
		t.Fatalf("wrote %d rows, live wrote %d\n got:  %v\n want: %v",
			len(got), len(c.Rows), got, c.Rows)
	}
	for i, w := range c.Rows {
		g := got[i]
		if g.Connected != w.Connected {
			t.Errorf("row %d: connected=%v, live=%v", i, g.Connected, w.Connected)
		}
		if g.TS != w.RowTs {
			t.Errorf("row %d: ts=%d, live=%d (a %dms difference — the observed/"+
				"declared rule)", i, g.TS, w.RowTs, g.TS-w.RowTs)
		}
		if g.ExplicitTS != (w.TsArg != nil) {
			t.Errorf("row %d: explicit=%v, live passed a timestamp=%v",
				i, g.ExplicitTS, w.TsArg != nil)
		}
		if g.Table != "connectivity" {
			t.Errorf("row %d: table=%q", i, g.Table)
		}
	}
	if len(status) != len(c.StatusEmits) {
		t.Errorf("emitted %d router:status, live emitted %d", len(status), len(c.StatusEmits))
		return
	}
	for i, w := range c.StatusEmits {
		if status[i] != w.Connected {
			t.Errorf("status %d: %v, live=%v", i, status[i], w.Connected)
		}
	}
}
