package alertpool

import (
	"encoding/json"
	"os"
	"sort"
	"testing"
)

// The lifecycle rule, against a corpus generated by DRIVING the live
// `syncSessions` (the alertpool-sync corpus).
//
// Reading the live function and reimplementing it is how a port acquires a
// difference nobody notices. This runs both.

type syncCorpus struct {
	Cases map[string]struct {
		Input struct {
			Live     map[string]bool `json:"live"`
			Active   string          `json:"active"`
			Excluded []string        `json:"excluded"`
			All      []struct {
				ID            string `json:"id"`
				AlertsEnabled bool   `json:"alertsEnabled"`
			} `json:"all"`
		} `json:"input"`
		Result struct {
			Built   []string `json:"built"`
			Stopped []string `json:"stopped"`
			After   []string `json:"after"`
		} `json:"result"`
	} `json:"cases"`
}

func TestPlanSyncMatchesLive(t *testing.T) {
	b, err := os.ReadFile("../../testdata/alertpool-sync-cases.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var c syncCorpus
	if err := json.Unmarshal(b, &c); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(c.Cases) == 0 {
		t.Fatal("corpus is empty — this test would pass against nothing")
	}

	for name, tc := range c.Cases {
		t.Run(name, func(t *testing.T) {
			all := make([]Router, 0, len(tc.Input.All))
			for _, r := range tc.Input.All {
				all = append(all, Router{ID: r.ID, AlertsEnabled: r.AlertsEnabled})
			}
			excl := map[string]bool{}
			for _, id := range tc.Input.Excluded {
				excl[id] = true
			}
			live := Live{}
			for k, v := range tc.Input.Live {
				live[k] = v
			}

			p := PlanSync(all, tc.Input.Active, excl)(live)

			// ── THE LIVE LOOP DROPS A FLAG-CHANGED SESSION AND REBUILDS IT ──
			//
			// It reports that router in BOTH `stopped` and `built`. This port
			// names it once, in Rebuild, because "tear down and build again" is
			// one decision and splitting it invites a caller to do half. The
			// comparison therefore folds Rebuild into both sides rather than
			// asserting the shapes match — the BEHAVIOUR is what must agree.
			built := idsOf(p.Build)
			built = append(built, p.Rebuild...)
			stopped := append([]string{}, p.Drop...)
			stopped = append(stopped, p.Rebuild...)
			sort.Strings(built)
			sort.Strings(stopped)

			eq(t, "built", built, tc.Result.Built)
			eq(t, "stopped", stopped, tc.Result.Stopped)

			// And the resulting session set.
			after := map[string]bool{}
			for id := range live {
				after[id] = true
			}
			for _, id := range p.Drop {
				delete(after, id)
			}
			for _, r := range p.Build {
				after[r.ID] = true
			}
			for _, id := range p.Rebuild {
				after[id] = true
			}
			got := make([]string, 0, len(after))
			for id := range after {
				got = append(got, id)
			}
			sort.Strings(got)
			eq(t, "after", got, tc.Result.After)
		})
	}
}

func idsOf(rs []Router) []string {
	out := make([]string, 0, len(rs))
	for _, r := range rs {
		out = append(out, r.ID)
	}
	return out
}

func eq(t *testing.T, what string, got, want []string) {
	t.Helper()
	if len(got) == 0 && len(want) == 0 {
		return
	}
	if len(got) != len(want) {
		t.Errorf("%s: got %v, live says %v", what, got, want)
		return
	}
	for i := range got {
		if got[i] != want[i] {
			t.Errorf("%s: got %v, live says %v", what, got, want)
			return
		}
	}
}

// ── THE FILTER THE LIVE FUNCTION DOES NOT DO ───────────────────────────────
//
// `syncSessions` never checks `disabled`; its callers pass an already-filtered
// list (`Routers.loadAll().filter(r => !r.disabled)`). This port filters inside
// PlanSync so a caller cannot forget, which is a deliberate difference and is
// therefore tested here rather than against the corpus.
func TestADisabledRouterGetsNoSession(t *testing.T) {
	p := PlanSync([]Router{
		{ID: "a"}, {ID: "b", Disabled: true},
	}, "", nil)(Live{})
	if got := idsOf(p.Build); len(got) != 1 || got[0] != "a" {
		t.Errorf("built %v — a disabled router is not connected to at all", got)
	}
}

// A running session for a router that has just been disabled must be dropped,
// not merely left out of Build.
func TestDisablingARouterDropsItsSession(t *testing.T) {
	p := PlanSync([]Router{{ID: "a", Disabled: true}}, "", nil)(Live{"a": false})
	if len(p.Drop) != 1 || p.Drop[0] != "a" {
		t.Errorf("Drop = %v, want [a]: a disabled router keeps its connection open", p.Drop)
	}
}

// AN EMPTY ID IS NOT A ROUTER. `activeID` is "" on a fresh install, and the
// exclusion `r.ID == activeID` would then match a record with no id.
func TestARouterWithNoIDIsNeverBuilt(t *testing.T) {
	p := PlanSync([]Router{{ID: ""}, {ID: "a"}}, "", nil)(Live{})
	if got := idsOf(p.Build); len(got) != 1 || got[0] != "a" {
		t.Errorf("built %v — an id-less record got a session", got)
	}
}
