package routeros

// Turning a connection failure into a sentence the Routers page can show.
//
// The port of `src/routeros/classifyError.js`. Without it every offline router
// reads "Connection failed", which is the fallback the background pool's
// `OnError` substitutes when nothing classified — and issue #92 exists precisely
// because "Offline" with no reason sends the operator to the container logs.
//
// ── THE BRANCHES ARE THE LIVE ONES; THE MATCHES CANNOT BE ───────────────────
//
// The live matcher reads NODE's error shapes: an `.errno` of `-111`, the string
// `ECONNREFUSED`, a `RosException` name. Go's errors carry none of those — a
// `net.OpError` says "connection refused", "no route to host", "i/o timeout".
//
// So this reproduces the CONDITION → REASON mapping rather than the regexes. A
// port that matched the live patterns literally would pass a test built from the
// live inputs and classify nothing at all in production, because no Go error
// contains the word ECONNREFUSED. `testdata/classify-error-cases.json` is
// generated by RUNNING the live module and carries both spellings per case, so
// the test feeds Go's and expects the live's answer.
//
// ── ORDER IS PART OF THE CONTRACT ───────────────────────────────────────────
//
// The original is an if/else-if chain, so the FIRST match wins and a message
// naming two conditions resolves the same way on both sides. The order below is
// its order, not a tidier one.
//
// THE CORPUS CARRIES TWO DELIBERATELY AMBIGUOUS CASES for that reason. Every
// other case names one condition, so the branches are disjoint and reordering
// them changes nothing — a mutation that swapped refused and timeout passed a
// full corpus, which is how the gap was found. "refused AND timed out" and
// "unreachable AND refused" resolve the two pairs that can actually collide.
//
// ── `*Trap` IS NODE'S `RosException` ────────────────────────────────────────
//
// Both mean "the device answered with an error" rather than "the socket
// failed", which is what that branch turns on. Node prints the driver's errno in
// brackets; a Trap has none, so nothing is fabricated and the bracket is omitted
// — the corpus pins the same shape by generating those cases with `errno: ''`.

import (
	"errors"
	"strings"
)

// Classification is what a connection error means, in the words the page shows.
//
// Hint is LOGGED ONLY. It names the exact RouterOS command an operator should
// run, which is useful in a log and is a description of the deployment in a
// browser.
type Classification struct {
	Reason string
	Hint   string
	// Classified is false when nothing matched, and Reason is then the RAW
	// driver message. A caller must not put an unclassified Reason in front of a
	// browser without passing it through safe.Message or substituting its own
	// generic string — the live header carries the same warning.
	Classified bool
}

// ClassifyError maps a dial or read failure onto a reason and an operator hint.
func ClassifyError(err error, host, port, user string, tls bool) Classification {
	if err == nil {
		return Classification{}
	}
	msg := err.Error()
	low := strings.ToLower(msg)
	has := func(s ...string) bool {
		for _, want := range s {
			if strings.Contains(low, want) {
				return true
			}
		}
		return false
	}
	out := func(reason, hint string) Classification {
		return Classification{Reason: reason, Hint: hint, Classified: reason != msg}
	}

	switch {
	case has("no route to host", "network is unreachable"):
		return out("Network unreachable — no route to "+host+" from the MikroDash host",
			"Check routing/VLAN between this container and "+host)

	case has("connection refused"):
		svc := "api"
		if tls {
			svc = "api-ssl"
		}
		return out("Connection refused — is RouterOS reachable at "+host+"?",
			"Check that the RouterOS API service is enabled: /ip service set "+svc+" disabled=no")

	case has("i/o timeout", "timed out"):
		return out("Connection timed out — check host and firewall rules",
			"Verify "+host+":"+port+" is reachable and not blocked by a firewall rule")

	case has("no such host"):
		return out("Host not found — check router host setting ("+host+")",
			"Ensure the hostname or IP address is correct and DNS is resolving")

	case has("connection reset"):
		return out("Connection reset by router",
			"The router closed the connection unexpectedly — check RouterOS logs")

	// CASE-SENSITIVE UPSTREAM: the live test is `/certificate/i`, so this stays
	// on the lowered copy like the rest. Go's TLS errors say "x509: certificate
	// signed by unknown authority", which lands here.
	case has("certificate"):
		return out(`TLS certificate error — try enabling "Allow self-signed cert"`,
			"Set tlsInsecure=true in settings or use a valid certificate on the router")

	// `cannot log in` is go-routeros's wording for a rejected login; the rest are
	// the live branch's own alternatives, kept so a differently-worded driver
	// still lands here.
	case has("cannot log in", "authentication", "login", "invalid user", "wrong password"):
		return out("Authentication failed — check username and password",
			`Confirm user "`+user+`" exists on the router and has API access: /user print`)
	}

	// The device answered with an error — node's RosException branch.
	var trap *Trap
	if errors.As(err, &trap) {
		if tls {
			return out("TLS handshake failed — check that RouterOS api-ssl is enabled",
				"Run: /ip service set api-ssl disabled=no  — and verify the certificate is valid")
		}
		return out("RouterOS API error — check that the API service is enabled and the user has API access",
			`Run: /ip service set api disabled=no  — then confirm user "`+user+`" has API group permissions`)
	}

	// Nothing matched. Reason is the raw message and Classified says so.
	return Classification{Reason: msg, Classified: false}
}
