package routeros

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// The corpus is generated by RUNNING `src/routeros/classifyError.js`, so the
// expected strings are the live module's own output rather than anything typed
// here. Each case carries BOTH spellings of its condition: `goMessage` is what a
// Go error says, and the reason/hint are what the live side produced for the
// node error meaning the same thing.
type classifyCase struct {
	Name       string `json:"name"`
	GoMessage  string `json:"goMessage"`
	GoTrap     bool   `json:"goTrap"`
	TLS        bool   `json:"tls"`
	Host       string `json:"host"`
	Port       string `json:"port"`
	User       string `json:"user"`
	Reason     string `json:"reason"`
	Hint       string `json:"hint"`
	Classified bool   `json:"classified"`
}

func loadClassifyCases(t *testing.T) []classifyCase {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "classify-error-cases.json"))
	if err != nil {
		t.Fatalf("corpus: %v (regenerate with tools/classify-error-cases.js)", err)
	}
	var cases []classifyCase
	if err := json.Unmarshal(body, &cases); err != nil {
		t.Fatal(err)
	}
	if len(cases) < 10 {
		t.Fatalf("corpus holds only %d cases — it is not the generated one", len(cases))
	}
	return cases
}

func TestClassifyErrorMatchesTheLiveModule(t *testing.T) {
	for _, c := range loadClassifyCases(t) {
		t.Run(c.Name, func(t *testing.T) {
			var err error
			if c.GoTrap {
				err = &Trap{Message: "unknown"}
			} else {
				err = errors.New(c.GoMessage)
			}
			got := ClassifyError(err, c.Host, c.Port, c.User, c.TLS)

			// An UNCLASSIFIED case must report the raw Go message, which is not
			// the live one — the live raw message is node's wording. So only the
			// FLAG is compared there; comparing the reason would be asserting
			// that Go and node phrase an unknown failure identically, which they
			// have no reason to.
			if !c.Classified {
				if got.Classified {
					t.Fatalf("classified %q, which the live module does not", c.GoMessage)
				}
				if got.Reason != c.GoMessage {
					t.Fatalf("unclassified reason = %q, want the raw message %q", got.Reason, c.GoMessage)
				}
				return
			}
			if !got.Classified {
				t.Fatalf("did not classify %q; live says %q", c.GoMessage, c.Reason)
			}
			if got.Reason != c.Reason {
				t.Errorf("reason\n  got  %q\n  live %q", got.Reason, c.Reason)
			}
			if got.Hint != c.Hint {
				t.Errorf("hint\n  got  %q\n  live %q", got.Hint, c.Hint)
			}
		})
	}
}

// The corpus must keep DISCRIMINATING. A classifier that returned one reason for
// everything would pass a corpus that had collapsed onto one reason, and this is
// what stops the corpus rotting into that quietly.
func TestClassifyCorpusStillDiscriminates(t *testing.T) {
	cases := loadClassifyCases(t)
	reasons := map[string]bool{}
	classified := 0
	for _, c := range cases {
		reasons[c.Reason] = true
		if c.Classified {
			classified++
		}
	}
	if len(reasons) < 8 {
		t.Fatalf("only %d distinct reasons across %d cases", len(reasons), len(cases))
	}
	if classified == len(cases) {
		t.Fatal("every case classifies — nothing exercises the raw-message fallback")
	}
}

// A nil error is not a failure to describe. The live module is never called with
// one, so this pins the port's own edge rather than a ported behaviour.
func TestClassifyNilIsEmpty(t *testing.T) {
	if got := ClassifyError(nil, "h", "8728", "u", false); got.Classified || got.Reason != "" {
		t.Fatalf("nil error produced %+v", got)
	}
}
