package routeros

// TestConnReason, judged against what the LIVE route's inline classifier
// answered for the same conditions.
//
// The corpus is generated by the test-reason corpus, which SLICES the
// handler out of `src/index.js` and runs it. Each case names a condition, the
// message the live side needs to reach that branch, and the message a Go error
// carries for the same condition — see the generator's header for why a literal
// port of the regexes would pass a naive test and classify nothing at runtime.
//
// Cases with neither a `goMessage` nor `goTrap` are LIVE-ONLY: they pin
// properties of the regexes (case sensitivity, branch order) that no Go error
// can exercise. They are asserted inside the generator, and counted here so that
// a corpus which quietly lost its Go inputs cannot look like a passing suite.

import (
	"encoding/json"
	"errors"
	"os"
	"strings"
	"testing"
)

type reasonCase struct {
	Condition     string `json:"condition"`
	LiveMessage   string `json:"liveMessage"`
	TLS           bool   `json:"tls"`
	GoMessage     string `json:"goMessage"`
	GoTrap        bool   `json:"goTrap"`
	GoTrapMessage string `json:"goTrapMessage"`
	Matched       bool   `json:"matched"`
	Reason        string `json:"reason"`
}

// goErr builds the error this port would produce for the case's condition, or
// reports that the case is live-only.
func (c reasonCase) goErr() (error, bool) {
	switch {
	case c.GoTrap:
		// Node's RosException is this port's *Trap: both mean "the device
		// answered with an error" rather than "the socket failed", which is what
		// the last branch turns on.
		//
		// With no message the case uses one matching NO branch, so it proves the
		// TYPE reached the branch rather than some word in the text having done
		// it. A case that names a message is asking the opposite question — see
		// `auth, capitalised device text`, where the device's own capitalised
		// words must still reach the authentication branch.
		msg := c.GoTrapMessage
		if msg == "" {
			msg = "unknown parameter"
		}
		return &Trap{Message: msg}, true
	case c.GoMessage != "":
		return errors.New(c.GoMessage), true
	}
	return nil, false
}

func loadReasonCases(t *testing.T) []reasonCase {
	t.Helper()
	b, err := os.ReadFile("../../testdata/test-reason-cases.json")
	if err != nil {
		t.Fatalf("corpus missing: %v — run tools/test-reason-cases.js", err)
	}
	var doc struct {
		Cases []reasonCase `json:"cases"`
	}
	if err := json.Unmarshal(b, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Cases) == 0 {
		t.Fatal("corpus is empty")
	}
	return doc.Cases
}

func TestTestConnReasonMatchesLive(t *testing.T) {
	cases := loadReasonCases(t)

	fed := 0
	for _, c := range cases {
		err, ok := c.goErr()
		if !ok {
			continue // live-only; the generator asserts these
		}
		fed++
		t.Run(c.Condition, func(t *testing.T) {
			got, matched := TestConnReason(err, c.TLS)
			if matched != c.Matched {
				t.Fatalf("matched = %v, live said %v\n  go input:  %v\n  live saw:  %s\n  live said: %q",
					matched, c.Matched, err, c.LiveMessage, c.Reason)
			}
			if got != c.Reason {
				t.Errorf("reason mismatch\n  go input: %v\n  got:  %q\n  live: %q", err, got, c.Reason)
			}
		})
	}

	// A corpus whose Go inputs all went null would skip every subtest above and
	// report a pass. THIRTEEN were fed when this was written — it was eighteen
	// before f4ade9e, because the last branch's four raw-`tls` inputs collapsed
	// to the two a boolean can take. The floor is a floor rather than the exact
	// number so that adding a case is not a failure; it is well below thirteen
	// because the number legitimately moves when upstream simplifies a branch,
	// and a gate that cries wolf on that gets raised until it means nothing.
	if fed < 10 {
		t.Errorf("only %d cases carried a Go input; the corpus lost them", fed)
	}
}

// TestEveryLiveSentenceIsReachableFromGo — the test above proves the port agrees
// with the live side on the cases it is fed. It does NOT prove the port can
// produce every sentence: a branch no Go error reaches is dead code that reads
// as ported.
//
// This asserts the two sets are equal, in both directions. A live sentence with
// no Go route is a gap; a Go sentence the live side never produces is invented.
func TestEveryLiveSentenceIsReachableFromGo(t *testing.T) {
	cases := loadReasonCases(t)

	live := map[string]bool{}
	reachable := map[string]bool{}
	for _, c := range cases {
		if c.Matched {
			live[c.Reason] = true
		}
		err, ok := c.goErr()
		if !ok {
			continue
		}
		if got, matched := TestConnReason(err, c.TLS); matched {
			reachable[got] = true
		}
	}
	for s := range live {
		if !reachable[s] {
			t.Errorf("no Go error in the corpus produces %q — the branch is unreachable "+
				"from this port, so add the Go spelling for its condition", s)
		}
	}
	for s := range reachable {
		if !live[s] {
			t.Errorf("this port produces %q, which the live classifier never does", s)
		}
	}
	if len(live) < 8 {
		t.Errorf("the corpus holds %d distinct sentences; the live classifier has 8", len(live))
	}
}

// TestTheLastBranchNamesTheServiceThatWasTRIED — the defect this port found,
// asserted as fixed rather than only carried by the corpus.
//
// The corpus holds both arms among twenty-four rows and a reader scanning the
// file would not see WHY they matter. This states it: the sentence tells the
// operator which RouterOS service to go and check, so it has to describe the
// connection that actually happened. It read the RAW request field until
// f4ade9e, which named the wrong service in both directions — absent meant TLS
// was on while the raw field was falsy, and the string "false" meant TLS was off
// while a non-empty string is truthy.
//
// `tls` here is the COERCED flag. If this function ever grows an `any` parameter
// again, that is the defect coming back.
func TestTheLastBranchNamesTheServiceThatWasTried(t *testing.T) {
	trap := &Trap{Message: "unknown parameter"}
	const handshake = "TLS handshake failed — check that RouterOS api-ssl is enabled"
	const plain = "RouterOS API error — check that api service is enabled and user has API access"

	if got, _ := TestConnReason(trap, true); got != handshake {
		t.Errorf("tls on: got %q, want %q", got, handshake)
	}
	if got, _ := TestConnReason(trap, false); got != plain {
		t.Errorf("tls off: got %q, want %q", got, plain)
	}
	// Each names the service it describes, which is the property that made the
	// old behaviour wrong rather than merely different: an operator told to
	// enable `api` when the attempt used `api-ssl` goes and changes the wrong
	// setting, and the test still fails.
	if !strings.Contains(handshake, "api-ssl") || !strings.Contains(plain, "api service") {
		t.Error("the two sentences stopped naming their services")
	}
	// The handshake sentence must NOT be the one a plain connection gets, and
	// vice versa — asserted as a difference so a future edit that collapses them
	// onto one string fails here rather than passing quietly.
	if handshake == plain {
		t.Error("the two arms are the same sentence")
	}
}

// TestAnUnmatchedErrorIsTheCallersProblem — the classifier must not sanitise,
// must not substitute a generic sentence, and must say so with the bool.
//
// The live code answers `sanitizeErr(e)` on this path. If this function returned
// the raw message with ok=true, a caller doing the obvious thing would put a
// driver string in front of a browser — and the string it would put there is the
// one below, which names the install's data directory.
func TestAnUnmatchedErrorIsTheCallersProblem(t *testing.T) {
	got, ok := TestConnReason(errors.New("unable to open database file: /data/mikrodash.db"), true)
	if ok {
		t.Errorf("an unclassifiable error reported ok=true")
	}
	if got != "" {
		t.Errorf("got %q; an unmatched error must return nothing, not the raw message", got)
	}
	if got, ok := TestConnReason(nil, true); ok || got != "" {
		t.Errorf("nil error: got (%q, %v), want (\"\", false)", got, ok)
	}
}

// TestTheBranchOrderIsTheLiveOrder — a SOURCE check, and the reason it is one is
// worth stating rather than apologising for.
//
// The live classifier is an if/else-if chain, so its order is observable: a
// message holding both "certificate" and "authentication" gets the certificate
// sentence, and the generator pins three such messages. NO GO ERROR CARRIES TWO
// OF THESE CONDITIONS. "connection refused" and "connection reset" cannot both
// appear; neither can an x509 failure and a login refusal. So over the inputs
// this port can actually receive, the branches are disjoint and reordering them
// changes nothing — two mutations (certificate below authentication, reset above
// refused) survived a full behavioural corpus for exactly that reason.
//
// THE SAME IS TRUE OF THE ALTERNATIVES INSIDE A BRANCH. go-routeros says
// "i/o timeout" and "cannot log in"; it never says "timed out" or
// "authentication" or "wrong password". Those spellings are carried because the
// live branch carries them and because a driver upgrade may start using one —
// which means deleting one today is free, passes every behavioural test, and is
// noticed only when it stops being free. Two more mutations survived on that.
//
// The honest options were to invent Go messages carrying two conditions, or
// worded the way no driver words them — fictional inputs in a corpus whose whole
// design is condition-based — or to check the chain where it is visible. This
// does the second, and claims nothing more than that.
func TestTheBranchOrderIsTheLiveOrder(t *testing.T) {
	src, err := os.ReadFile("testreason.go")
	if err != nil {
		t.Fatal(err)
	}
	// The live chain, in its order, with every alternative each branch accepts.
	want := [][]string{
		{"connection refused"},
		{"i/o timeout", "timed out"},
		{"no such host", "server misbehaving"},
		{"connection reset"},
		{"certificate"},
		{"cannot log in", "authentication", "login", "invalid user", "wrong password"},
	}
	var got [][]string
	for _, line := range strings.Split(string(src), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "case has(") {
			continue
		}
		args := line[len("case has("):strings.LastIndex(line, ")")]
		var conds []string
		for _, a := range strings.Split(args, ",") {
			conds = append(conds, strings.Trim(strings.TrimSpace(a), `"`))
		}
		got = append(got, conds)
	}
	if len(got) != len(want) {
		t.Fatalf("found %d branches, expected %d\n  got:  %v\n  want: %v\n"+
			"A branch was added or removed. Decide where it sits in the live chain, "+
			"then update this list and tools/test-reason-cases.js together.", len(got), len(want), got, want)
	}
	for i := range want {
		if strings.Join(got[i], "|") != strings.Join(want[i], "|") {
			t.Errorf("branch %d accepts %v; the live chain's branch there accepts %v\n"+
				"If a driver upgrade made one of these unnecessary, say so here and in "+
				"the branch's comment — do not delete it silently.", i, got[i], want[i])
		}
	}
	// The last branch is not a `case` and would not be seen above. It must stay
	// last: it is the only one that answers on the TYPE of the error rather than
	// its text, so a `*Trap` whose message happens to say "cannot log in" has to
	// reach the authentication branch first — which the corpus case
	// `auth, capitalised device text` proves it does.
	body := string(src)
	if strings.Index(body, "errors.As(err, &trap)") < strings.LastIndex(body, "case has(") {
		t.Error("the *Trap branch moved above the text branches; a device saying " +
			"\"cannot log in\" would then get the api-ssl sentence")
	}
}
