package routeros

// The sentence a FAILED CONNECTION TEST shows the operator.
//
// ── THIS IS NOT ClassifyError, AND MERGING THEM WOULD CHANGE THE UI ─────────
//
// `classify.go` next door does the same job for a different consumer: the
// Routers page's offline reason (#92). The two classifiers are separate on the
// live side too, they disagree on the wording, and they disagree on the branch
// lists. For a refused connection this one says
//
//	Connection refused — check host and port
//
// and that one says
//
//	Connection refused — is RouterOS reachable at 10.0.0.2?
//
// The first is right for a modal where the operator is typing the host and port
// into the two fields above the button; the second is right for a page listing
// routers they are not editing. Sharing an implementation would change one of
// them, which a port may not do.
//
// It lives in THIS package rather than in `internal/routers` for the same reason
// `classify.go` does: the last branch turns on whether the device answered — a
// `*Trap` — and reaching for that from another package would need either an
// import cycle or an invented duplicate of `Trap`.
//
// ── THE BRANCHES ARE THE LIVE ONES; THE MATCHES CANNOT BE ───────────────────
//
// The live classifier reads NODE's error shapes: `ECONNREFUSED`, `ENOTFOUND`, an
// `.errno` of `CANTLOGIN`, a `RosException` name. Go's errors carry none of
// them. So this reproduces the CONDITION → SENTENCE mapping, not the regexes.
// `testdata/test-reason-cases.json` is generated by RUNNING the live handler and
// carries both spellings per case; the test feeds Go's and expects the live's
// answer.
//
// ORDER IS PART OF THE CONTRACT. The original is an if/else-if chain, so the
// first match wins. The corpus carries three deliberately ambiguous messages —
// certificate-and-authentication, refused-and-timed-out, login-and-RosException
// — because every other case names one condition, and a reordering that changes
// nothing on disjoint inputs is exactly the mutation a full corpus lets through.
//
// ── TWO DEFECTS THIS PORT FOUND HERE, BOTH FIXED UPSTREAM ──────────────────
//
// The test-reason corpus lifts the live handler into a `vm` and runs it.
// That route needs a live server stack, so neither side had ever EXECUTED this
// classifier in a test — it had only been read. Two things fell out of the first
// run, both fixed in f4ade9e, and this port follows the fix rather than
// reproducing the old behaviour:
//
//  1. The last branch read `body.tls`, the RAW request field, where every other
//     decision in the route used the coerced `testTls`. It now reads the coerced
//     one, so this function takes a plain bool and the request's JavaScript
//     truthiness is somebody else's problem — `internal/routers/endpoint.go`'s.
//  2. RouterOS's own words for a rejected login, "invalid user name or
//     password", matched none of the alternatives, so the commonest failure of
//     the button showed the raw driver message. `invalid user` and `wrong
//     password` were added; this port's list already had both, copied from
//     `classifyError.js`.
//
// ── AND THE CAUSE, WHICH IS ONE THING RATHER THAN TWO ───────────────────────
//
// Both were a SECOND COPY of one decision drifting from the original.
// `classifyError.js` is canonical — its own header records that it was extracted
// from inline precisely so it would be reachable everywhere — and the route kept
// a duplicate anyway, which then fell a pattern behind for about a year.
//
// The generator now carries a ledger comparing the two ALTERNATIVE SETS, so the
// next divergence fails a gate rather than waiting for somebody to run the
// button. Collapsing the two classifiers is the real fix and is upstream's, kept
// for after the cutover because it rewords several other messages and the JS
// wording is this port's oracle until then.

import (
	"errors"
	"strings"
)

// TestConnReason returns the sentence for a failed connection test, and whether
// any branch matched.
//
// An unmatched error is the CALLER's problem: the live code answers
// `sanitizeErr(e)` there, and putting a redaction policy inside a classifier
// would make it impossible to tell which of the two produced a given string.
//
// `tls` is the COERCED flag — the one the connection was actually attempted
// with, not the raw request field. That distinction is the whole of defect 1
// above: the sentence tells the operator which RouterOS service to go and check,
// so it has to describe the connection that happened.
func TestConnReason(err error, tls bool) (string, bool) {
	if err == nil {
		return "", false
	}
	low := strings.ToLower(err.Error())
	has := func(s ...string) bool {
		for _, want := range s {
			if strings.Contains(low, want) {
				return true
			}
		}
		return false
	}

	switch {
	case has("connection refused"):
		return "Connection refused — check host and port", true

	case has("i/o timeout", "timed out"):
		return "Connection timed out — check host and firewall rules", true

	case has("no such host", "server misbehaving"):
		return "Host not found — check router host/IP", true

	case has("connection reset"):
		return "Connection reset by router", true

	// Go's TLS failures say "x509: certificate signed by unknown authority",
	// which lands here — and lands here BEFORE the tls/handshake branch below,
	// exactly as `/certificate/i` precedes the RosException branch upstream.
	case has("certificate"):
		return `TLS certificate error — try enabling "Allow self-signed cert"`, true

	// `cannot log in` is go-routeros's wording for a rejected login. The rest are
	// the live branch's own alternatives, kept so that a differently-worded
	// driver still lands here rather than in the sanitiser.
	case has("cannot log in", "authentication", "login", "invalid user", "wrong password"):
		return "Authentication failed — check username and password", true
	}

	// The device answered with an error, or the TLS handshake never got as far as
	// a certificate to complain about — node's RosException branch. A `*Trap` is
	// the first; "first record does not look like a TLS handshake" is what Go
	// says for the second, which is precisely the api/api-ssl mix-up the two
	// sentences below exist to explain.
	var trap *Trap
	if errors.As(err, &trap) || has("handshake", "tls:") {
		return rosExceptionReason("", tls), true
	}
	return "", false
}

// rosExceptionReason is the last branch, and the only one that reads anything
// beyond the error.
//
// ── IT READS THE COERCED FLAG, AND DID NOT ALWAYS ──────────────────────────
//
// It tested `body.tls` — the raw request field — until f4ade9e. The two
// disagree in BOTH directions:
//
//	absent   the coerced value is TRUE, TLS defaults on, but the raw field is
//	         falsy: a connection over api-ssl was blamed on the plain `api`.
//	"false"  the coerced value is FALSE, but a non-empty string is truthy: a
//	         plain connection was blamed on a handshake that never happened.
//
// Both were wrong in the same way — the sentence named a service the attempt
// did not use, and the operator went and checked it. The test-reason corpus
// fails if `body.tls` reappears in that branch, so this note cannot outlive the
// behaviour it describes.
//
// errno is always "" from this port. Node prints the driver's number in brackets
// and a Trap has none, so nothing is fabricated and the bracket is omitted; the
// corpus generates those cases with `errno: ”` so the two sides agree exactly.
// The parameter stays because the SUFFIX MOVES between the two arms — before the
// em dash on one, after the sentence on the other — and a reader deleting it
// would tidy away a difference the corpus pins.
func rosExceptionReason(errno string, tls bool) string {
	suffix := ""
	if errno != "" {
		suffix = " [" + errno + "]"
	}
	if tls {
		return "TLS handshake failed — check that RouterOS api-ssl is enabled" + suffix
	}
	return "RouterOS API error" + suffix + " — check that api service is enabled and user has API access"
}
