package geo

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"testing"

	"mikrodash/internal/geoplace"
)

// The corpus is generated by RUNNING `src/cityIndex.js` over geoip-lite's own
// data, so `hits` is the live module's answer — ranking included.
//
// A geoip-lite data refresh changes these answers. That is drift to regenerate,
// which `--check` reports; it is not a port defect, and NOTHING here asserts a
// record count, exactly as the live header forbids.
type cityCase struct {
	Q     string  `json:"q"`
	Limit any     `json:"limit"`
	Hits  []Place `json:"hits"`
}

func loadCityCases(t *testing.T) []cityCase {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "city-index-cases.json"))
	if err != nil {
		t.Fatalf("corpus: %v (regenerate with tools/city-index-cases.js)", err)
	}
	var doc struct {
		Cases []cityCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Cases) < 20 {
		t.Fatalf("the corpus holds %d queries — it is not the generated one", len(doc.Cases))
	}
	return doc.Cases
}

// limitArg renders the corpus's raw limit the way a query parameter would
// arrive. `null` means the caller passed none.
func limitArg(v any) string {
	switch x := v.(type) {
	case nil:
		return ""
	case string:
		return x
	case float64:
		if x == float64(int64(x)) {
			return strconv.FormatInt(int64(x), 10)
		}
		return strconv.FormatFloat(x, 'f', -1, 64)
	default:
		return ""
	}
}

func TestCitySearchMatchesTheLiveModule(t *testing.T) {
	dir := dataDir(t) // skips when geoip-lite data is absent
	idx, err := BuildCityIndex(dir)
	if err != nil {
		t.Fatalf("BuildCityIndex: %v", err)
	}

	for _, c := range loadCityCases(t) {
		name := c.Q + "/" + limitArg(c.Limit)
		t.Run(name, func(t *testing.T) {
			got := idx.Search(c.Q, limitArg(c.Limit))
			if len(got) != len(c.Hits) {
				t.Fatalf("got %d hits, live has %d", len(got), len(c.Hits))
			}
			for i := range got {
				a, _ := json.Marshal(got[i])
				b, _ := json.Marshal(c.Hits[i])
				if string(a) != string(b) {
					t.Errorf("hit %d\n  got  %s\n  live %s", i, a, b)
				}
			}
		})
	}
}

// THE LIMIT RULES, which read as though 0 and -3 behave alike and do not.
//
// `parseInt(0) || 20` is 20 because zero is FALSY, so asking for none returns the
// default; a negative parses truthy and is clamped up to 1. Pinned here as well
// as in the corpus because the expression invites exactly the wrong reading.
func TestLimitClamping(t *testing.T) {
	cases := []struct {
		raw  string
		want int
	}{
		{"", 20}, {"0", 20}, {"abc", 20},
		{"-3", 1}, {"1", 1}, {"7", 7},
		{"20.9", 20}, {"999", 50}, {"50", 50}, {"51", 50},
	}
	for _, c := range cases {
		if got := clampLimit(c.raw); got != c.want {
			t.Errorf("clampLimit(%q) = %d, want %d", c.raw, got, c.want)
		}
	}
}

// A one-letter query is refused before the index is even consulted — it matches
// thousands of places and is never a real intent.
func TestShortQueriesAreRefused(t *testing.T) {
	idx := &CityIndex{}
	for _, q := range []string{"", " ", "a", " a "} {
		if got := idx.Search(q, ""); len(got) != 0 {
			t.Errorf("Search(%q) returned %d hits", q, len(got))
		}
	}
}

// ── THE SEARCH AND THE VALIDATOR MUST AGREE (issue #120) ────────────────────
//
// `GET /api/cities` hands the picker a Place; the picker posts it straight back;
// `geoplace.NormalizePlace` decides whether it is storable. Nothing connected
// those two ends, and they drifted: geoip-lite's fixed 3-byte region field was
// replaced by DB-IP's full subdivision names, the validator kept the old rule,
// and choosing any town answered 400 "Pick a town from the list, or clear the
// location" — advice the user had already followed.
//
// It is checked HERE, over the index's own output, because that is the only
// place both halves are in scope. A test on either side alone is what let this
// through: each was self-consistent.
//
// The gazetteer is built from the same JSON shape `cmd/geogen` writes, with the
// awkward real values in it rather than tidy ones — a fixture of "BE" would pass
// against the exact bug this exists to prevent.
func TestEveryPlaceTheSearchReturnsSurvivesNormalizePlace(t *testing.T) {
	dir := t.TempDir()
	rows := []map[string]any{}
	// Enough rows to clear the index's own "this file holds almost nothing"
	// floor, then the ones that matter.
	for i := 0; i < minRows; i++ {
		rows = append(rows, map[string]any{
			"name": "Filler" + strconv.Itoa(i), "region": "Fillershire",
			"cc": "GB", "lat": 51.5, "lon": -0.1, "w": 1,
		})
	}
	for _, r := range []map[string]any{
		{"name": "Marl", "region": "North Rhine-Westphalia", "cc": "DE",
			"lat": 51.6567, "lon": 7.09038, "w": 100},
		{"name": "Stuttgart", "region": "Baden-Württemberg", "cc": "DE",
			"lat": 48.78, "lon": 9.18, "w": 100},
		{"name": "Nice", "region": "Provence-Alpes-Côte d'Azur", "cc": "FR",
			"lat": 43.7, "lon": 7.26, "w": 100},
		{"name": "Motomachi", "region": "34", "cc": "JP",
			"lat": 34.4, "lon": 132.4, "w": 100},
		{"name": "Nowhere", "region": "", "cc": "AQ", "lat": -75.0, "lon": 0.0, "w": 100},
	} {
		rows = append(rows, r)
	}
	b, err := json.Marshal(rows)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, gazetteerName), b, 0o600); err != nil {
		t.Fatal(err)
	}

	idx, err := BuildCityIndex(dir)
	if err != nil {
		t.Fatalf("BuildCityIndex: %v", err)
	}

	checked := 0
	for _, q := range []string{"Marl", "Stuttgart", "Nice", "Motomachi", "Nowhere"} {
		got := idx.Search(q, "5")
		if len(got) == 0 {
			t.Errorf("%q returned nothing; the fixture or the search changed and "+
				"this test is no longer checking what it claims", q)
			continue
		}
		for _, p := range got {
			checked++
			// EXACTLY what the client posts back: the JSON the API sent,
			// decoded the way the server decodes an untrusted body.
			enc, err := json.Marshal(p)
			if err != nil {
				t.Fatal(err)
			}
			var body any
			if err := json.Unmarshal(enc, &body); err != nil {
				t.Fatal(err)
			}
			if geoplace.NormalizePlace(body) == nil {
				t.Errorf("the search returned a place its own validator refuses: %s\n"+
					"a user picking this town cannot save it, and the message tells "+
					"them to pick from the list — which is what they just did", enc)
			}
		}
	}
	if checked == 0 {
		t.Fatal("nothing was checked")
	}
}
