package rbac

// PlanUserGrants, judged against what the LIVE syncUserGrants actually did.
//
// The corpus is generated by the syncgrants corpus, which slices the
// function out of `src/rbac.js` and runs it with the database and the router
// store stubbed. What those stubs recorded IS the expectation: the ORDERED
// operations, not a summary of them.
//
// Order is load-bearing here in a way a set comparison would miss. The delete is
// unconditional and comes first; a port that upserted before deleting would
// destroy what it had just written, and would look correct in any test that
// compared final grants.

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

type grantCase struct {
	Why  string `json:"why"`
	User struct {
		ID               string `json:"id"`
		Username         string `json:"username"`
		Role             string `json:"role"`
		AllowedRouterIDs any    `json:"allowedRouterIds"`
		Absent           bool   `json:"allowedRouterIdsAbsent"`
	} `json:"user"`
	RouterIDs []string `json:"routerIds"`
	Made      int      `json:"made"`
	Ops       []struct {
		Op        string `json:"op"`
		Role      string `json:"role"`
		ScopeType string `json:"scopeType"`
		ScopeID   string `json:"scopeId"`
		Text      string `json:"text"`
	} `json:"ops"`
}

func loadGrantCases(t *testing.T) []grantCase {
	t.Helper()
	b, err := os.ReadFile("../../testdata/syncgrants-cases.json")
	if err != nil {
		t.Fatalf("corpus missing: %v — run tools/syncgrants-cases.js", err)
	}
	var doc struct {
		Cases []grantCase `json:"cases"`
	}
	if err := json.Unmarshal(b, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Cases) == 0 {
		t.Fatal("corpus is empty")
	}
	return doc.Cases
}

func (c grantCase) plan() GrantPlan {
	live := map[string]bool{}
	for _, id := range c.RouterIDs {
		live[id] = true
	}
	return PlanUserGrants(UserForGrants{
		ID: c.User.ID, Username: c.User.Username, Role: c.User.Role,
		AllowedRouterIDs: c.User.AllowedRouterIDs,
	}, live)
}

func TestPlanUserGrantsMatchesLive(t *testing.T) {
	for _, c := range loadGrantCases(t) {
		t.Run(c.Why, func(t *testing.T) {
			got := c.plan()

			var want []GrantStep
			var wantWarn []string
			for _, o := range c.Ops {
				switch o.Op {
				case "delete":
					want = append(want, GrantStep{Op: "delete"})
				case "upsert":
					want = append(want, GrantStep{Op: "upsert", Role: o.Role,
						ScopeType: o.ScopeType, ScopeID: o.ScopeID})
				case "warn":
					wantWarn = append(wantWarn, o.Text)
				}
				// `bump` is deliberately not compared: it is the live module's own
				// cache generation, which this port does not have. It is RECORDED
				// in the corpus so its disappearance stays visible, rather than
				// dropped at generation time where nobody would ever see it go.
			}

			if len(got.Steps) != len(want) {
				t.Fatalf("%d steps, live did %d\n  got:  %+v\n  want: %+v",
					len(got.Steps), len(want), got.Steps, want)
			}
			for i := range want {
				if got.Steps[i] != want[i] {
					t.Errorf("step %d: got %+v, live did %+v", i, got.Steps[i], want[i])
				}
			}
			if got.Made != c.Made {
				t.Errorf("Made = %d, live returned %d", got.Made, c.Made)
			}
			if len(got.Warnings) != len(wantWarn) {
				t.Fatalf("%d warnings, live logged %d\n  got:  %q\n  want: %q",
					len(got.Warnings), len(wantWarn), got.Warnings, wantWarn)
			}
			for i := range wantWarn {
				// The live call is `console.warn('%s', msg)`, so the recorded text
				// carries the format string ahead of the message. Compared on
				// CONTAINMENT, which is the part an operator greps for; comparing
				// the whole string would pin the stub's joining rather than the
				// wording.
				if !strings.Contains(wantWarn[i], got.Warnings[i]) {
					t.Errorf("warning %d:\n  got:  %q\n  live: %q", i, got.Warnings[i], wantWarn[i])
				}
			}
		})
	}
}

// TestTheEmptyListIsUnrestricted — the inversion, stated on its own.
//
// The corpus carries five spellings of it among twenty-three rows, and a reader
// scanning that file would not see they are one decision or why it is the
// dangerous one. Getting it backwards locks out every unrestricted user on the
// first run after cutover, including — on a fresh install — the only
// administrator there is.
func TestTheEmptyListIsUnrestricted(t *testing.T) {
	fleet := map[string]bool{"r1": true, "r2": true}
	u := UserForGrants{ID: "u1", Username: "ann", Role: "admin"}

	for name, ids := range map[string]any{
		"an empty list":           []any{},
		"nil":                     nil,
		"a string":                "r1",
		"a list of empty strings": []any{"", ""},
		"a list of zeros":         []any{0.0},
		"a list of nulls":         []any{nil, nil},
		"a Go empty slice":        []string{},
		"a Go slice of one empty": []string{""},
		"a number, not a list":    8729.0,
		"a bool, not a list":      true,
	} {
		u.AllowedRouterIDs = ids
		got := PlanUserGrants(u, fleet)
		if got.Made != 1 {
			t.Errorf("%s: Made = %d, want 1 — this user has NO access at all", name, got.Made)
			continue
		}
		last := got.Steps[len(got.Steps)-1]
		if last.ScopeType != "global" {
			t.Errorf("%s: got scope %q, want global — an empty allowedRouterIds means "+
				"UNRESTRICTED, not no routers", name, last.ScopeType)
		}
	}
}

// TestTheLockoutIsDistinctFromTheEmptyCase.
//
// Both produce no router-scoped grant, and they must not produce the same thing:
// all-unknown ids leave the user with NOTHING (the delete already ran), while an
// empty list gives them everything. A port collapsing the two would either lock
// out a restricted user or hand a global grant to somebody whose routers were
// deleted.
func TestTheLockoutIsDistinctFromTheEmptyCase(t *testing.T) {
	fleet := map[string]bool{"r1": true}

	locked := PlanUserGrants(UserForGrants{ID: "u1", Username: "lee", Role: "admin",
		AllowedRouterIDs: []any{"gone"}}, fleet)
	if locked.Made != 0 {
		t.Errorf("all-unknown: Made = %d, want 0", locked.Made)
	}
	// The DELETE still happened. That is what makes it a lockout rather than a
	// no-op, and it is the only way this function removes access.
	if len(locked.Steps) != 1 || locked.Steps[0].Op != "delete" {
		t.Errorf("all-unknown steps = %+v, want exactly one delete", locked.Steps)
	}
	if len(locked.Warnings) != 1 {
		t.Errorf("%d warnings, want 1 — the operator has no other way to learn why",
			len(locked.Warnings))
	}

	open := PlanUserGrants(UserForGrants{ID: "u1", Username: "ann", Role: "admin",
		AllowedRouterIDs: []any{}}, fleet)
	if open.Made != 1 {
		t.Errorf("empty list: Made = %d, want 1", open.Made)
	}
	if open.Steps[len(open.Steps)-1].ScopeType != "global" {
		t.Errorf("empty list did not produce a global grant: %+v", open.Steps)
	}
}

// TestAMalformedUserTouchesNothing.
//
// The id check comes before the delete. Reversed — deleted first, checked after
// — a call with a missing id wipes the grants of whoever the caller meant, and
// returns 0 as if nothing had happened.
func TestAMalformedUserTouchesNothing(t *testing.T) {
	fleet := map[string]bool{"r1": true}
	for _, u := range []UserForGrants{
		{ID: "", Username: "vic", Role: "admin"},
		{Username: "wes", Role: "admin", AllowedRouterIDs: []any{"r1"}},
		{},
	} {
		got := PlanUserGrants(u, fleet)
		if len(got.Steps) != 0 || got.Made != 0 || len(got.Warnings) != 0 {
			t.Errorf("%+v produced %+v — a user with no id must not even delete", u, got.Steps)
		}
	}
}

// TestAnUnknownRoleIsAViewer — least privilege, in both scopes.
//
// The role is applied to router-scoped grants as well as global ones, and a port
// validating only the global path would hand every restricted user the raw
// stored string. `db.UpsertGrant` falls back to `readonly` for an unrecognised
// role, so that mistake would be survivable there and invisible — which is
// exactly why it is checked here.
func TestAnUnknownRoleIsAViewer(t *testing.T) {
	fleet := map[string]bool{"r1": true}
	for _, role := range []string{"superuser", "", "Admin", "ADMIN", "operator ", "root"} {
		for _, ids := range []any{[]any{}, []any{"r1"}} {
			got := PlanUserGrants(UserForGrants{ID: "u1", Username: "x", Role: role,
				AllowedRouterIDs: ids}, fleet)
			last := got.Steps[len(got.Steps)-1]
			if last.Role != "viewer" {
				t.Errorf("role %q with ids %v became %q, want viewer — least privilege is the "+
					"right way to be wrong about a role", role, ids, last.Role)
			}
		}
	}
	// And the two that ARE recognised survive, or the ladder collapsed the other
	// way and nobody can be an administrator.
	for role, want := range map[string]string{"admin": "admin", "operator": "operator"} {
		got := PlanUserGrants(UserForGrants{ID: "u1", Username: "x", Role: role,
			AllowedRouterIDs: []any{}}, fleet)
		if got.Steps[len(got.Steps)-1].Role != want {
			t.Errorf("role %q became %q, want %q", role, got.Steps[len(got.Steps)-1].Role, want)
		}
	}
}

// TestANumericIdMatchesAStringOne.
//
// `String(1)` is "1", not "1.000000" and not "1e+06". JSON hands Go a float64,
// and the obvious `fmt.Sprintf("%v")` is right for 1 and wrong for a large id —
// so the conversion is pinned on values where the formats diverge.
func TestANumericIdMatchesAStringOne(t *testing.T) {
	fleet := map[string]bool{"1": true, "1000000": true}
	got := PlanUserGrants(UserForGrants{ID: "u1", Username: "ivy", Role: "viewer",
		AllowedRouterIDs: []any{1.0, 1000000.0}}, fleet)
	if got.Made != 2 {
		t.Fatalf("Made = %d, want 2 — a numeric id did not match its stored string form: %+v\n"+
			"warnings: %q", got.Made, got.Steps, got.Warnings)
	}
	if got.Steps[1].ScopeID != "1" || got.Steps[2].ScopeID != "1000000" {
		t.Errorf("scope ids = %q, %q; want \"1\", \"1000000\"",
			got.Steps[1].ScopeID, got.Steps[2].ScopeID)
	}
}
