package resource

// Replays testdata/res-preview-cases.json — generated by running the LIVE
// `previewCommand` — into the ported one.
//
// The preview is rendered in a browser and can be copied out of it, so a secret
// that reaches it is a credential in a screenshot. The corpus therefore carries
// the case a VALUE-keyed mask gets wrong: an ordinary field holding exactly the
// secret's text, where the ordinary one must stay visible.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

type previewCase struct {
	Name      string            `json:"name"`
	Key       string            `json:"key"`
	ID        *string           `json:"id"`
	Invalid   bool              `json:"invalid"`
	Command   string            `json:"command"`
	Validated map[string]string `json:"validated"`
	Editing   bool              `json:"editing"`
}

func TestPreviewCommandMatchesTheLiveModule(t *testing.T) {
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "res-preview-cases.json"))
	if err != nil {
		t.Fatalf("no corpus — run: node tools/res-preview-cases.js: %v", err)
	}
	var payload struct {
		Cases []previewCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		t.Fatal(err)
	}

	checked, masked := 0, 0
	for _, c := range payload.Cases {
		c := c
		if c.Invalid {
			continue
		}
		t.Run(c.Name, func(t *testing.T) {
			r := ByKey(c.Key)
			if r == nil {
				t.Fatalf("resource %q is not in this port's registry", c.Key)
			}
			id := ""
			if c.ID != nil {
				id = *c.ID
			}
			// Driven from the LIVE side's validated values, so a difference in
			// the command cannot be blamed on a different `validate`. That is a
			// deliberate narrowing: `options_test.go` compares the schemas, and
			// this compares only the rendering.
			got := r.PreviewCommand(Validated{Values: c.Validated, Editing: c.Editing}, id)
			if got != c.Command {
				t.Errorf("preview differs\n  live: %s\n  port: %s", c.Command, got)
			}
			checked++
			if strings.Contains(got, "«set»") {
				masked++
			}
			// THE ABSOLUTE RULE, asserted on the port's own output rather than
			// only through equality: no secret VALUE may appear. If both sides
			// ever leaked together, the comparison above would pass and this
			// would not.
			for _, f := range r.Fields {
				if f.Type != TypeSecret {
					continue
				}
				if v := c.Validated[f.Name]; v != "" && strings.Contains(got, "="+f.ROS+"="+v) {
					t.Errorf("the preview leaks the secret %q: %s", f.Name, got)
				}
			}
		})
	}

	if checked == 0 {
		t.Fatal("no usable case in the corpus")
	}
	if masked == 0 {
		t.Error("no case masked a secret — this suite cannot see a preview that leaks one")
	}
	if masked == checked {
		t.Error("every case masked — this suite cannot see one that masks everything")
	}
	t.Logf("%d previews compared, %d carrying a masked secret", checked, masked)
}
