package collection

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The corpus is generated by RUNNING `src/collection.js`, so `want` is the live
// module's own answer rather than anything typed here.
type resolveCase struct {
	Name     string         `json:"name"`
	Settings map[string]any `json:"settings"`
	Record   *struct {
		DefaultIf  any `json:"defaultIf"`
		PingTarget any `json:"pingTarget"`
		Collection *struct {
			Mode      string `json:"mode"`
			Off       any    `json:"off"`
			Overrides any    `json:"overrides"`
		} `json:"collection"`
	} `json:"record"`
	Fingerprint string `json:"fingerprint"`
	Want        struct {
		Mode      string          `json:"mode"`
		Poll      map[string]int  `json:"poll"`
		Stream    map[string]bool `json:"stream"`
		Enabled   map[string]bool `json:"enabled"`
		Overrides map[string]any  `json:"overrides"`
	} `json:"want"`
}

func loadCases(t *testing.T) []resolveCase {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "collection-cases.json"))
	if err != nil {
		t.Fatalf("corpus: %v (regenerate with tools/collection-cases.js)", err)
	}
	var doc struct {
		Cases []resolveCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Cases) < 20 {
		t.Fatalf("corpus holds %d cases — it is not the generated one", len(doc.Cases))
	}
	return doc.Cases
}

// routerFor rebuilds the Router the live case was given.
//
// `off` and `overrides` arrive as `any` on purpose: the corpus deliberately
// carries a case where `off` is a STRING and one where `overrides` is a string,
// because a hand-edited routers.json can hold either and the live side ignores
// both. Decoding them into typed fields directly would make those cases
// unrepresentable — the harness would fix the input the test exists to check.
func routerFor(c resolveCase) *Router {
	if c.Record == nil || c.Record.Collection == nil {
		return nil
	}
	cc := c.Record.Collection
	r := &Router{Mode: cc.Mode}
	if list, ok := cc.Off.([]any); ok {
		for _, v := range list {
			if s, ok := v.(string); ok {
				r.Off = append(r.Off, s)
			}
		}
	}
	if m, ok := cc.Overrides.(map[string]any); ok {
		r.Overrides = m
	}
	return r
}

func TestResolveMatchesTheLiveModule(t *testing.T) {
	for _, c := range loadCases(t) {
		t.Run(c.Name, func(t *testing.T) {
			got := Resolve(c.Settings, routerFor(c))

			if got.Mode != c.Want.Mode {
				t.Errorf("mode = %q, live says %q", got.Mode, c.Want.Mode)
			}
			for k, want := range c.Want.Poll {
				if got.Poll[k] != want {
					t.Errorf("poll[%s] = %d, live says %d", k, got.Poll[k], want)
				}
			}
			if len(got.Poll) != len(c.Want.Poll) {
				t.Errorf("poll has %d keys, live has %d", len(got.Poll), len(c.Want.Poll))
			}
			for k, want := range c.Want.Stream {
				if got.Stream[k] != want {
					t.Errorf("stream[%s] = %v, live says %v", k, got.Stream[k], want)
				}
			}
			for k, want := range c.Want.Enabled {
				if got.Enabled[k] != want {
					t.Errorf("enabled[%s] = %v, live says %v", k, got.Enabled[k], want)
				}
			}
		})
	}
}

// The EMBEDDED registry must match the one the corpus was generated from. They
// come from the same generator run, so this catches an asset edited by hand and
// a half-applied regeneration — not a live-side change, which `--check` catches.
func TestTheEmbeddedRegistryMatchesTheCorpus(t *testing.T) {
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "collection-cases.json"))
	if err != nil {
		t.Fatal(err)
	}
	var doc struct {
		Cases []resolveCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatal(err)
	}
	// Every collector the corpus resolved must exist in the embedded registry,
	// and vice versa — a row dropped from either side is the failure here.
	want := map[string]bool{}
	for k := range doc.Cases[0].Want.Enabled {
		want[k] = true
	}
	got := map[string]bool{}
	for _, c := range Collectors() {
		got[c.Key] = true
	}
	for k := range want {
		if !got[k] {
			t.Errorf("the corpus resolved %q, which the embedded registry does not hold", k)
		}
	}
	for k := range got {
		if !want[k] {
			t.Errorf("the embedded registry holds %q, which the corpus never resolved", k)
		}
	}
}

// The registry must keep the SHAPE the resolver depends on. A table that arrived
// with every `pollable` false would make every collector a stream and still
// satisfy the corpus if the corpus were regenerated from it.
func TestTheRegistryStillDiscriminates(t *testing.T) {
	var pollable, streamKeyed, disableable, withDeps int
	for _, c := range Collectors() {
		if c.Pollable {
			pollable++
		}
		if c.StreamKey != "" {
			streamKeyed++
		}
		if c.Disableable {
			disableable++
		}
		if len(c.Requires) > 0 {
			withDeps++
		}
	}
	if pollable == 0 || pollable == len(Collectors()) {
		t.Errorf("%d of %d collectors are pollable — the non-pollable branch is unreachable",
			pollable, len(Collectors()))
	}
	if streamKeyed == 0 {
		t.Error("no collector has a streamKey — the override branch is unreachable")
	}
	if disableable == 0 {
		t.Error("no collector is disableable — the off list can do nothing")
	}
	if withDeps == 0 {
		t.Error("no collector declares a dependency — the cascade is unreachable")
	}
}

func TestFingerprintMatchesTheLiveModule(t *testing.T) {
	seen := map[string]string{}
	for _, c := range loadCases(t) {
		t.Run(c.Name, func(t *testing.T) {
			var extras RecordExtras
			if c.Record != nil {
				extras = RecordExtras{DefaultIf: c.Record.DefaultIf, PingTarget: c.Record.PingTarget}
			}
			got := Fingerprint(c.Settings, routerFor(c), extras)
			if got != c.Fingerprint {
				t.Errorf("fingerprint\n  got  %s\n  live %s", got, c.Fingerprint)
			}
		})
		seen[c.Name] = c.Fingerprint
	}

	// THE POINT OF THE FINGERPRINT, asserted rather than assumed: two inputs that
	// RESOLVE identically must still differ here when a field outside
	// `collection` differs, or a router edit would skip a rebuild it needs.
	if seen["settings topN"] == seen["defaults: no settings, no record"] {
		t.Error("a settings key outside `collection` did not change the fingerprint")
	}
	// And the coercion asymmetry between the two groups: a RECORD extra of 0 is
	// indistinguishable from empty, a SETTINGS extra of 0 is not.
	if seen["a record extra that is ZERO"] != seen["a record extra that is EMPTY"] {
		t.Error("a record extra of 0 and of \"\" fingerprinted differently")
	}
	if seen["a settings extra that is ZERO"] == seen["defaults: no settings, no record"] {
		t.Error("a settings extra of 0 fingerprinted as absent")
	}
}
