package collect

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	"mikrodash/internal/routeros"
)

// The corpus is generated by tools/ping-cases.js from the LIVE collector. See
// that file for why each expectation is produced by running the original rather
// than by writing down what it ought to do.
type pingCorpus struct {
	LossWindow int `json:"lossWindow"`
	MaxHistory int `json:"maxHistory"`
	ParseRTT   []struct {
		In  string   `json:"in"`
		Out *float64 `json:"out"`
	} `json:"parseRtt"`
	Cases []struct {
		Name    string              `json:"name"`
		Packets []map[string]string `json:"packets"`
		Steps   []struct {
			RTT     *float64 `json:"rtt"`
			Loss    *int     `json:"loss"`
			MinRTT  *float64 `json:"minRtt"`
			MaxRTT  *float64 `json:"maxRtt"`
			Emitted bool     `json:"emitted"`
		} `json:"steps"`
		HistoryLen int `json:"historyLen"`
		History    []struct {
			RTT  *float64 `json:"rtt"`
			Loss *int     `json:"loss"`
		} `json:"history"`
	} `json:"cases"`
}

func loadPingCorpus(t *testing.T) pingCorpus {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("testdata", "ping-cases.json"))
	if err != nil {
		t.Fatalf("no corpus — run: node tools/ping-cases.js: %v", err)
	}
	var c pingCorpus
	if err := json.Unmarshal(body, &c); err != nil {
		t.Fatal(err)
	}
	if len(c.Cases) < 10 || len(c.ParseRTT) < 20 {
		t.Fatalf("the corpus is too small to prove anything: %d cases, %d values",
			len(c.Cases), len(c.ParseRTT))
	}
	return c
}

func f64eq(a, b *float64) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	return math.Abs(*a-*b) < 1e-9
}

// TestParsePingRTTMatchesTheLiveParser walks every value the corpus recorded,
// including the compound `1ms438us` the RouterOS documentation shows and no
// fixture contains.
func TestParsePingRTTMatchesTheLiveParser(t *testing.T) {
	c := loadPingCorpus(t)
	for _, v := range c.ParseRTT {
		got := ParsePingRTT(v.In)
		if !f64eq(got, v.Out) {
			t.Errorf("ParsePingRTT(%q) = %v, live gives %v", v.In, fmtP(got), fmtP(v.Out))
		}
	}
}

func fmtP(v *float64) string {
	if v == nil {
		return "nil"
	}
	return json.Number(json.Number("")).String() + fmtFloat(*v)
}

func fmtFloat(v float64) string {
	b, _ := json.Marshal(v)
	return string(b)
}

// TestPingSequencesMatchTheLiveCollector drives the same packet sequences
// through this collector and compares rtt, loss, min/max AND whether the emit
// fingerprint let the payload through — the last of which is what stops a
// steady link re-emitting an identical payload every second.
func TestPingSequencesMatchTheLiveCollector(t *testing.T) {
	c := loadPingCorpus(t)
	for _, cs := range c.Cases {
		t.Run(cs.Name, func(t *testing.T) {
			p := NewPing(nil, func(string, string, any) {}, 5000, "198.51.100.1")
			for i, pkt := range cs.Packets {
				row := routeros.Reply{}
				for k, v := range pkt {
					row[k] = v
				}
				out := p.ProcessRow(row, int64(1000+i))
				want := cs.Steps[i]

				if (out != nil) != want.Emitted {
					t.Fatalf("packet %d (%v): emitted=%v, live emitted=%v",
						i, pkt, out != nil, want.Emitted)
				}
				// `last` is updated on EVERY packet, emitted or not — that is
				// what a newly-focused viewer is replayed.
				last := p.Last()
				if !f64eq(last.RTT, want.RTT) {
					t.Errorf("packet %d (%v): rtt %v, live %v", i, pkt, fmtP(last.RTT), fmtP(want.RTT))
				}
				if (last.Loss == nil) != (want.Loss == nil) ||
					(last.Loss != nil && *last.Loss != *want.Loss) {
					t.Errorf("packet %d (%v): loss %v, live %v", i, pkt, last.Loss, want.Loss)
				}
				if !f64eq(last.MinRTT, want.MinRTT) {
					t.Errorf("packet %d (%v): minRtt %v, live %v", i, pkt, fmtP(last.MinRTT), fmtP(want.MinRTT))
				}
				if !f64eq(last.MaxRTT, want.MaxRTT) {
					t.Errorf("packet %d (%v): maxRtt %v, live %v", i, pkt, fmtP(last.MaxRTT), fmtP(want.MaxRTT))
				}
			}
			hist := p.History()
			if len(hist.History) != cs.HistoryLen {
				t.Fatalf("history has %d points, live has %d", len(hist.History), cs.HistoryLen)
			}
			for i, want := range cs.History {
				got := hist.History[i]
				if !f64eq(got.RTT, want.RTT) {
					t.Errorf("history[%d].rtt = %v, live %v", i, fmtP(got.RTT), fmtP(want.RTT))
				}
				if (got.Loss == nil) != (want.Loss == nil) ||
					(got.Loss != nil && *got.Loss != *want.Loss) {
					t.Errorf("history[%d].loss = %v, live %v", i, got.Loss, want.Loss)
				}
			}
		})
	}
}

// TestPingConstantsMatchTheLiveOnes — the window width and history cap are the
// two numbers the whole card's behaviour hangs on.
func TestPingConstantsMatchTheLiveOnes(t *testing.T) {
	c := loadPingCorpus(t)
	if c.LossWindow != pingLossWindow {
		t.Errorf("loss window is %d here and %d over there", pingLossWindow, c.LossWindow)
	}
	if c.MaxHistory != pingMaxHistory {
		t.Errorf("history cap is %d here and %d over there", pingMaxHistory, c.MaxHistory)
	}
}

// TestPingIntervalIsClampedToRouterOSsLimit. RouterOS caps /tool/ping's interval
// at five seconds and does not reject a larger one — it ignores it, which would
// leave this side believing it had configured something it had not.
func TestPingIntervalIsClampedToRouterOSsLimit(t *testing.T) {
	for _, c := range []struct {
		pollMs int
		want   int
	}{
		{0, 1}, {1, 1}, {499, 1}, {500, 1}, {1000, 1}, {1499, 1}, {1500, 2},
		{2000, 2}, {5000, 5}, {5499, 5}, {5500, 5}, {30000, 5}, {600000, 5},
	} {
		if got := pingIntervalSec(c.pollMs); got != c.want {
			t.Errorf("pingIntervalSec(%d) = %d, want %d", c.pollMs, got, c.want)
		}
	}
}

// TestPingSummaryPacketsAreSkipped. RouterOS ends a run with a summary carrying
// neither a time nor a status. Feeding one to ProcessRow would push a LOST
// result into the rolling window — a row with no status reads as replied, and a
// row with no time has no rtt — so the card would show a phantom timeout after
// every burst.
//
// This exists because the rule lived inline in the stream callback, where no
// corpus reaches it and a mutation removing it survived.
func TestPingSummaryPacketsAreSkipped(t *testing.T) {
	skip := []routeros.Reply{
		{},
		{"sent": "5", "received": "5", "packet-loss": "0%"},
		{"min-rtt": "1ms", "avg-rtt": "1ms", "max-rtt": "3ms"},
		{"host": "198.51.100.1", "size": "56"},
	}
	for _, row := range skip {
		if pingIsResult(row) {
			t.Errorf("%v was treated as a result; it is a summary and must be skipped", row)
		}
	}
	keep := []routeros.Reply{
		{"time": "13ms"},
		{"response-time": "13ms"},
		{"status": "timeout"},
		{"status": "echo reply", "time": "1ms"},
		// A zero time is still a result: `0ms` is the fastest reply, not an
		// absent one, and the original's test is on the KEY being present.
		{"time": "0ms"},
	}
	for _, row := range keep {
		if !pingIsResult(row) {
			t.Errorf("%v was skipped as a summary; it is a result", row)
		}
	}
	// And the consequence, driven through the collector: a summary must not
	// move the loss figure.
	p := NewPing(nil, func(string, string, any) {}, 5000, "198.51.100.1")
	p.ProcessRow(routeros.Reply{"time": "10ms"}, 1)
	before := *p.Last().Loss
	if pingIsResult(routeros.Reply{"sent": "5"}) {
		p.ProcessRow(routeros.Reply{"sent": "5"}, 2)
	}
	if got := *p.Last().Loss; got != before {
		t.Errorf("a summary packet moved loss from %d%% to %d%%", before, got)
	}
}

// ── the stream path itself ──────────────────────────────────────────────────
//
// Everything above drives ProcessRow directly, which is where the arithmetic
// lives — and it left four behaviours untested, all of which a mutation walked
// straight past: whether the summary skip is actually WIRED into the callback,
// and the whole permission-denied latch. This fake stands in for the client so
// the collector's own plumbing is on trial.

type fakePingStream struct {
	rows    []routeros.Reply
	err     error
	started int
	stopped int
	conn    bool
}

func (f *fakePingStream) Do(routeros.Cmd) ([]routeros.Reply, error) { return nil, nil }
func (f *fakePingStream) Connected() bool                           { return f.conn }
func (f *fakePingStream) Stream(_ routeros.Cmd, onRow func(routeros.Reply)) (func(), error) {
	f.started++
	if f.err != nil {
		return nil, f.err
	}
	for _, r := range f.rows {
		onRow(r)
	}
	return func() { f.stopped++ }, nil
}

// TestPingSummaryIsSkippedByTheSTREAM — the predicate has its own test; this is
// about whether the callback calls it. A mutation deleting the guard from the
// callback survived until this existed.
func TestPingSummaryIsSkippedByTheSTREAM(t *testing.T) {
	f := &fakePingStream{conn: true, rows: []routeros.Reply{
		{"time": "10ms"},
		{"sent": "5", "received": "5", "packet-loss": "0%"}, // the summary
		{"time": "10ms"},
	}}
	var emits int
	p := NewPing(f, func(string, string, any) { emits++ }, 5000, "198.51.100.1")
	p.Start()

	h := p.History()
	if len(h.History) != 2 {
		t.Fatalf("history has %d points, want 2 — the summary was not skipped", len(h.History))
	}
	if got := *p.Last().Loss; got != 0 {
		t.Errorf("loss is %d%% after two replies and a summary; the summary counted as a timeout", got)
	}
}

// TestPingPermissionDeniedLatches. /tool/ping needs the `test` policy. Without
// it every retry fails identically, so the refusal is recorded once, emitted so
// the card can explain itself, and not retried until the router reconnects.
func TestPingPermissionDeniedLatches(t *testing.T) {
	for _, msg := range []string{
		"not enough privileges", "permission denied (9)",
		"cannot run this command", "NOT ENOUGH PRIVILEGES",
	} {
		t.Run(msg, func(t *testing.T) {
			f := &fakePingStream{conn: true, err: errString(msg)}
			var events []string
			p := NewPing(f, func(_, ev string, _ any) { events = append(events, ev) }, 5000, "1.1.1.1")
			p.Start()

			if !p.Denied() {
				t.Fatal("the refusal did not latch")
			}
			if len(events) != 1 || events[0] != "ping:update" {
				t.Errorf("emitted %v, want one ping:update so the card can say why it is blank", events)
			}
			last := p.Last()
			if last == nil || !last.PermissionDenied {
				t.Fatalf("the payload does not carry permissionDenied: %+v", last)
			}
			if last.RTT != nil || last.Loss != nil {
				t.Errorf("a refusal carried an rtt/loss: %+v", last)
			}
			// AND IT DOES NOT RETRY.
			before := f.started
			p.Start()
			p.Resume()
			if f.started != before {
				t.Errorf("the stream was reopened %d more times after a refusal", f.started-before)
			}
			// A reconnect may be to a router whose user DOES have the policy, so
			// the latch must not survive one.
			//
			// The fake's error is cleared first, deliberately. An earlier
			// version left it set and then asserted the latch was clear after
			// Reconnected — which FAILED, and the port was right: clearing the
			// latch and immediately retrying against a router that still
			// refuses re-latches, exactly as the original does. What is being
			// tested is that the latch does not outlive the reconnect, not that
			// a refusing router is forgiven.
			f.err = nil
			p.Reconnected()
			if p.Denied() {
				t.Error("the latch survived a reconnect to a router that now permits ping")
			}
			if f.started == before {
				t.Error("Reconnected did not reopen the stream")
			}
		})
	}
}

// A transient error must NOT latch: the next reconnect or resume should try again.
func TestPingTransientErrorDoesNotLatch(t *testing.T) {
	f := &fakePingStream{conn: true, err: errString("connection reset by peer")}
	p := NewPing(f, func(string, string, any) {}, 5000, "1.1.1.1")
	p.Start()
	if p.Denied() {
		t.Fatal("a transient error latched as a permission refusal")
	}
	before := f.started
	p.Resume()
	if f.started <= before {
		t.Error("Resume did not retry after a transient error")
	}
}

type errString string

func (e errString) Error() string { return string(e) }
