package collect

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"sync"
	"testing"

	"mikrodash/internal/routeros"
)

// The corpus is generated by tools/ping-cases.js from the LIVE collector. See
// that file for why each expectation is produced by running the original rather
// than by writing down what it ought to do.
type pingCorpus struct {
	LossWindow int `json:"lossWindow"`
	MaxHistory int `json:"maxHistory"`
	ParseRTT   []struct {
		In  string   `json:"in"`
		Out *float64 `json:"out"`
	} `json:"parseRtt"`
	Cases []struct {
		Name    string              `json:"name"`
		Packets []map[string]string `json:"packets"`
		Steps   []struct {
			RTT     *float64 `json:"rtt"`
			Loss    *int     `json:"loss"`
			MinRTT  *float64 `json:"minRtt"`
			MaxRTT  *float64 `json:"maxRtt"`
			Emitted bool     `json:"emitted"`
		} `json:"steps"`
		HistoryLen int `json:"historyLen"`
		History    []struct {
			RTT  *float64 `json:"rtt"`
			Loss *int     `json:"loss"`
		} `json:"history"`
	} `json:"cases"`
}

func loadPingCorpus(t *testing.T) pingCorpus {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("testdata", "ping-cases.json"))
	if err != nil {
		t.Fatalf("no corpus — run: node tools/ping-cases.js: %v", err)
	}
	var c pingCorpus
	if err := json.Unmarshal(body, &c); err != nil {
		t.Fatal(err)
	}
	if len(c.Cases) < 10 || len(c.ParseRTT) < 20 {
		t.Fatalf("the corpus is too small to prove anything: %d cases, %d values",
			len(c.Cases), len(c.ParseRTT))
	}
	return c
}

func f64eq(a, b *float64) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	return math.Abs(*a-*b) < 1e-9
}

// TestParsePingRTTMatchesTheLiveParser walks every value the corpus recorded,
// including the compound `1ms438us` the RouterOS documentation shows and no
// fixture contains.
func TestParsePingRTTMatchesTheLiveParser(t *testing.T) {
	c := loadPingCorpus(t)
	for _, v := range c.ParseRTT {
		got := ParsePingRTT(v.In)
		if !f64eq(got, v.Out) {
			t.Errorf("ParsePingRTT(%q) = %v, live gives %v", v.In, fmtP(got), fmtP(v.Out))
		}
	}
}

func fmtP(v *float64) string {
	if v == nil {
		return "nil"
	}
	return json.Number(json.Number("")).String() + fmtFloat(*v)
}

func fmtFloat(v float64) string {
	b, _ := json.Marshal(v)
	return string(b)
}

// TestPingSequencesMatchTheLiveCollector drives the same packet sequences
// through this collector and compares rtt, loss, min/max AND whether the emit
// fingerprint let the payload through — the last of which is what stops a
// steady link re-emitting an identical payload every second.
func TestPingSequencesMatchTheLiveCollector(t *testing.T) {
	c := loadPingCorpus(t)
	for _, cs := range c.Cases {
		t.Run(cs.Name, func(t *testing.T) {
			p := NewPing(nil, func(string, string, any) {}, 5000, "198.51.100.1")
			for i, pkt := range cs.Packets {
				row := routeros.Reply{}
				for k, v := range pkt {
					row[k] = v
				}
				out := p.ProcessRow(row, int64(1000+i))
				want := cs.Steps[i]

				if (out != nil) != want.Emitted {
					t.Fatalf("packet %d (%v): emitted=%v, live emitted=%v",
						i, pkt, out != nil, want.Emitted)
				}
				// `last` is updated on EVERY packet, emitted or not — that is
				// what a newly-focused viewer is replayed.
				last := p.Last()
				if !f64eq(last.RTT, want.RTT) {
					t.Errorf("packet %d (%v): rtt %v, live %v", i, pkt, fmtP(last.RTT), fmtP(want.RTT))
				}
				if (last.Loss == nil) != (want.Loss == nil) ||
					(last.Loss != nil && *last.Loss != *want.Loss) {
					t.Errorf("packet %d (%v): loss %v, live %v", i, pkt, last.Loss, want.Loss)
				}
				if !f64eq(last.MinRTT, want.MinRTT) {
					t.Errorf("packet %d (%v): minRtt %v, live %v", i, pkt, fmtP(last.MinRTT), fmtP(want.MinRTT))
				}
				if !f64eq(last.MaxRTT, want.MaxRTT) {
					t.Errorf("packet %d (%v): maxRtt %v, live %v", i, pkt, fmtP(last.MaxRTT), fmtP(want.MaxRTT))
				}
			}
			hist := p.History()
			if len(hist.History) != cs.HistoryLen {
				t.Fatalf("history has %d points, live has %d", len(hist.History), cs.HistoryLen)
			}
			for i, want := range cs.History {
				got := hist.History[i]
				if !f64eq(got.RTT, want.RTT) {
					t.Errorf("history[%d].rtt = %v, live %v", i, fmtP(got.RTT), fmtP(want.RTT))
				}
				if (got.Loss == nil) != (want.Loss == nil) ||
					(got.Loss != nil && *got.Loss != *want.Loss) {
					t.Errorf("history[%d].loss = %v, live %v", i, got.Loss, want.Loss)
				}
			}
		})
	}
}

// TestPingConstantsMatchTheLiveOnes — the window width and history cap are the
// two numbers the whole card's behaviour hangs on.
func TestPingConstantsMatchTheLiveOnes(t *testing.T) {
	c := loadPingCorpus(t)
	if c.LossWindow != pingLossWindow {
		t.Errorf("loss window is %d here and %d over there", pingLossWindow, c.LossWindow)
	}
	if c.MaxHistory != pingMaxHistory {
		t.Errorf("history cap is %d here and %d over there", pingMaxHistory, c.MaxHistory)
	}
}

// TestPingIntervalIsClampedToRouterOSsLimit. RouterOS caps /tool/ping's interval
// at five seconds and does not reject a larger one — it ignores it, which would
// leave this side believing it had configured something it had not.
func TestPingIntervalIsClampedToRouterOSsLimit(t *testing.T) {
	for _, c := range []struct {
		pollMs int
		want   int
	}{
		{0, 1}, {1, 1}, {499, 1}, {500, 1}, {1000, 1}, {1499, 1}, {1500, 2},
		{2000, 2}, {5000, 5}, {5499, 5}, {5500, 5}, {30000, 5}, {600000, 5},
	} {
		if got := pingIntervalSec(c.pollMs); got != c.want {
			t.Errorf("pingIntervalSec(%d) = %d, want %d", c.pollMs, got, c.want)
		}
	}
}

// TestPingSummaryPacketsAreSkipped. RouterOS ends a run with a summary carrying
// neither a time nor a status. Feeding one to ProcessRow would push a LOST
// result into the rolling window — a row with no status reads as replied, and a
// row with no time has no rtt — so the card would show a phantom timeout after
// every burst.
//
// This exists because the rule lived inline in the stream callback, where no
// corpus reaches it and a mutation removing it survived.
func TestPingSummaryPacketsAreSkipped(t *testing.T) {
	skip := []routeros.Reply{
		{},
		{"sent": "5", "received": "5", "packet-loss": "0%"},
		{"min-rtt": "1ms", "avg-rtt": "1ms", "max-rtt": "3ms"},
		{"host": "198.51.100.1", "size": "56"},
	}
	for _, row := range skip {
		if pingIsResult(row) {
			t.Errorf("%v was treated as a result; it is a summary and must be skipped", row)
		}
	}
	keep := []routeros.Reply{
		{"time": "13ms"},
		{"response-time": "13ms"},
		{"status": "timeout"},
		{"status": "echo reply", "time": "1ms"},
		// A zero time is still a result: `0ms` is the fastest reply, not an
		// absent one, and the original's test is on the KEY being present.
		{"time": "0ms"},
	}
	for _, row := range keep {
		if !pingIsResult(row) {
			t.Errorf("%v was skipped as a summary; it is a result", row)
		}
	}
	// And the consequence, driven through the collector: a summary must not
	// move the loss figure.
	p := NewPing(nil, func(string, string, any) {}, 5000, "198.51.100.1")
	p.ProcessRow(routeros.Reply{"time": "10ms"}, 1)
	before := *p.Last().Loss
	if pingIsResult(routeros.Reply{"sent": "5"}) {
		p.ProcessRow(routeros.Reply{"sent": "5"}, 2)
	}
	if got := *p.Last().Loss; got != before {
		t.Errorf("a summary packet moved loss from %d%% to %d%%", before, got)
	}
}

// ── the stream path itself ──────────────────────────────────────────────────
//
// Everything above drives ProcessRow directly, which is where the arithmetic
// lives — and it left four behaviours untested, all of which a mutation walked
// straight past: whether the summary skip is actually WIRED into the callback,
// and the whole permission-denied latch. This fake stands in for the client so
// the collector's own plumbing is on trial.

type fakePingStream struct {
	rows    []routeros.Reply
	err     error
	started int
	stopped int
	conn    bool
}

func (f *fakePingStream) Do(routeros.Cmd) ([]routeros.Reply, error) { return nil, nil }
func (f *fakePingStream) Connected() bool                           { return f.conn }
func (f *fakePingStream) Stream(_ routeros.Cmd, onRow func(routeros.Reply)) (func(), error) {
	f.started++
	if f.err != nil {
		return nil, f.err
	}
	for _, r := range f.rows {
		onRow(r)
	}
	return func() { f.stopped++ }, nil
}

// TestPingSummaryIsSkippedByTheSTREAM — the predicate has its own test; this is
// about whether the callback calls it. A mutation deleting the guard from the
// callback survived until this existed.
func TestPingSummaryIsSkippedByTheSTREAM(t *testing.T) {
	f := &fakePingStream{conn: true, rows: []routeros.Reply{
		{"time": "10ms"},
		{"sent": "5", "received": "5", "packet-loss": "0%"}, // the summary
		{"time": "10ms"},
	}}
	var emits int
	p := NewPing(f, func(string, string, any) { emits++ }, 5000, "198.51.100.1")
	p.Start()

	h := p.History()
	if len(h.History) != 2 {
		t.Fatalf("history has %d points, want 2 — the summary was not skipped", len(h.History))
	}
	if got := *p.Last().Loss; got != 0 {
		t.Errorf("loss is %d%% after two replies and a summary; the summary counted as a timeout", got)
	}
}

// TestPingPermissionDeniedLatches. /tool/ping needs the `test` policy. Without
// it every retry fails identically, so the refusal is recorded once, emitted so
// the card can explain itself, and not retried until the router reconnects.
func TestPingPermissionDeniedLatches(t *testing.T) {
	for _, msg := range []string{
		"not enough privileges", "permission denied (9)",
		"cannot run this command", "NOT ENOUGH PRIVILEGES",
	} {
		t.Run(msg, func(t *testing.T) {
			f := &fakePingStream{conn: true, err: errString(msg)}
			var events []string
			p := NewPing(f, func(_, ev string, _ any) { events = append(events, ev) }, 5000, "1.1.1.1")
			p.Start()

			if !p.Denied() {
				t.Fatal("the refusal did not latch")
			}
			if len(events) != 1 || events[0] != "ping:update" {
				t.Errorf("emitted %v, want one ping:update so the card can say why it is blank", events)
			}
			last := p.Last()
			if last == nil || !last.PermissionDenied {
				t.Fatalf("the payload does not carry permissionDenied: %+v", last)
			}
			if last.RTT != nil || last.Loss != nil {
				t.Errorf("a refusal carried an rtt/loss: %+v", last)
			}
			// AND IT DOES NOT RETRY.
			before := f.started
			p.Start()
			p.Resume()
			if f.started != before {
				t.Errorf("the stream was reopened %d more times after a refusal", f.started-before)
			}
			// A reconnect may be to a router whose user DOES have the policy, so
			// the latch must not survive one.
			//
			// The fake's error is cleared first, deliberately. An earlier
			// version left it set and then asserted the latch was clear after
			// Reconnected — which FAILED, and the port was right: clearing the
			// latch and immediately retrying against a router that still
			// refuses re-latches, exactly as the original does. What is being
			// tested is that the latch does not outlive the reconnect, not that
			// a refusing router is forgiven.
			f.err = nil
			p.Reconnected()
			if p.Denied() {
				t.Error("the latch survived a reconnect to a router that now permits ping")
			}
			if f.started == before {
				t.Error("Reconnected did not reopen the stream")
			}
		})
	}
}

// A transient error must NOT latch: the next reconnect or resume should try again.
func TestPingTransientErrorDoesNotLatch(t *testing.T) {
	f := &fakePingStream{conn: true, err: errString("connection reset by peer")}
	p := NewPing(f, func(string, string, any) {}, 5000, "1.1.1.1")
	p.Start()
	if p.Denied() {
		t.Fatal("a transient error latched as a permission refusal")
	}
	before := f.started
	p.Resume()
	if f.started <= before {
		t.Error("Resume did not retry after a transient error")
	}
}

type errString string

func (e errString) Error() string { return string(e) }

// ── B.5: THE INTERVAL THE STREAM CANNOT EXPRESS ────────────────────────────
//
// RouterOS caps `/tool/ping`'s interval at five seconds and does not reject a
// larger one: it accepts it silently and ignores it. So an operator asking for a
// ping every thirty seconds got one every five — six times as many as they asked
// for, with nothing anywhere saying so.
//
// `pingIntervalSec` has clamped to [1,5] since the port and its comment says
// exactly this. What was missing is a path that can honour the setting.

// pollDoer is a Streamer that can also answer a command, and counts both.
type pollDoer struct {
	mu      sync.Mutex
	streams int
	dos     int
	rows    []routeros.Reply
}

func (d *pollDoer) Connected() bool { return true }

func (d *pollDoer) Stream(routeros.Cmd, func(routeros.Reply)) (func(), error) {
	d.mu.Lock()
	d.streams++
	d.mu.Unlock()
	return func() {}, nil
}

func (d *pollDoer) Do(routeros.Cmd) ([]routeros.Reply, error) {
	d.mu.Lock()
	d.dos++
	rows := d.rows
	d.mu.Unlock()
	return rows, nil
}

func (d *pollDoer) counts() (streams, dos int) {
	d.mu.Lock()
	defer d.mu.Unlock()
	return d.streams, d.dos
}

// TestAFastPingStreamsAndASlowOnePolls is the whole of B.5.
//
// FIVE SECONDS IS THE LINE, and it is not arbitrary: it is what RouterOS will
// actually honour. Every default and every install today sits at or below it and
// keeps streaming, so this changes nothing for them.
func TestAFastPingStreamsAndASlowOnePolls(t *testing.T) {
	for _, tc := range []struct {
		name         string
		pollMs       int
		wantStream   bool
		wantPollPath bool
	}{
		{"the default", 5000, true, false},
		{"faster than the cap", 1000, true, false},
		{"exactly the cap", 5000, true, false},
		{"beyond what a stream can carry", 30000, false, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			d := &pollDoer{}
			p := NewPing(d, func(string, string, any) {}, tc.pollMs, "1.1.1.1")
			if got := p.pollsRatherThanStreams(); got != tc.wantPollPath {
				t.Fatalf("at %dms pollsRatherThanStreams = %v, want %v — the line is "+
					"five seconds, which is what RouterOS will honour",
					tc.pollMs, got, tc.wantPollPath)
			}
			p.Start()
			defer p.Stop()

			streams, _ := d.counts()
			if tc.wantStream && streams != 1 {
				t.Errorf("%d channel(s) opened, want 1", streams)
			}
			if !tc.wantStream && streams != 0 {
				t.Errorf("%d channel(s) opened for an interval a stream cannot carry; "+
					"the router would silently ping every 5s instead of every %ds",
					streams, tc.pollMs/1000)
			}
		})
	}
}

// TestTheSlowPathTakesReadingsAndSkipsTheSummary.
//
// `/tool/ping` ends a run with a summary sentence carrying neither a time nor a
// status. Feeding one to ProcessRow pushes a LOST result into the history on
// every successful ping, which is the bug `pingIsResult` exists to prevent — and
// the polled path had to be given the same guard rather than inheriting it.
func TestTheSlowPathTakesReadingsAndSkipsTheSummary(t *testing.T) {
	d := &pollDoer{rows: []routeros.Reply{
		{"seq": "0", "time": "12ms", "status": ""},
		{"sent": "1", "received": "1", "packet-loss": "0"}, // the summary
	}}
	var emitted int
	p := NewPing(d, func(string, string, any) { emitted++ }, 30000, "1.1.1.1")

	p.pollOnce()

	if _, dos := d.counts(); dos != 1 {
		t.Errorf("%d command(s) issued for one reading, want 1", dos)
	}
	if emitted != 1 {
		t.Errorf("%d payload(s) emitted, want 1 — the summary sentence was counted as "+
			"a result, which pushes a LOST reading into the history on every "+
			"successful ping", emitted)
	}
}

// TestAPollingPingStopsCleanly. Its loop is a goroutine; a collector that leaves
// one running after Stop keeps pinging a router nobody is watching.
func TestAPollingPingStopsCleanly(t *testing.T) {
	d := &pollDoer{}
	p := NewPing(d, func(string, string, any) {}, 30000, "1.1.1.1")
	p.Start()
	p.Stop()
	p.mu.Lock()
	loop := p.loop
	p.mu.Unlock()
	if loop != nil {
		t.Error("Stop left the poll loop in place")
	}
}

// ── PHASE 4.1: A SEQUENCE DERIVATION IS A FOLD ─────────────────────────────
//
// The five set-A derivations map over a whole table, because a table IS the
// current state. `ping`'s rows are a SEQUENCE — each element matters once — and
// the plan left it "blocked behind set B" as though it needed a different layer.
//
// It needs the same signature with a different arity:
//
//	table     func(prior, []Reply) (payload, prior)
//	sequence  func(prior,   Reply) (payload, prior)
//
// `ProcessRow` was already the fold; it carried its state on a receiver, which is
// what made these cases unreachable.

func TestFoldPingIsPureInItsPriorState(t *testing.T) {
	// ── SPARE CAPACITY IS THE WHOLE TEST, AND THE FIRST VERSION HAD NONE ────
	//
	// Written with slice literals this passed even against `append(prior.Window,
	// …)`: a literal's capacity equals its length, so append reallocates and the
	// caller's array is untouched by accident. The mutation survived.
	//
	// A ring that has been sliced down — which is exactly what these are after
	// the first `[1:]` — carries spare capacity, so append writes THROUGH into
	// the state the caller still holds. That is the case that occurs in
	// production and the only one that distinguishes a copy from a write.
	prior := PingFold{
		Window:  append(make([]bool, 0, 8), true, true),
		History: append(make([]PingPoint, 0, 8), PingPoint{TS: 1}),
	}
	priorWin := append([]bool(nil), prior.Window...)
	_, next, _ := FoldPing(prior, "1.1.1.1", 5000, routeros.Reply{"time": "10ms"}, 99)

	// THE PRIOR MUST NOT HAVE BEEN WRITTEN. `append` on a slice with spare
	// capacity writes THROUGH to the caller's backing array, which is how a fold
	// that looks pure corrupts the state it was handed — the same class of defect
	// as ParsePPPSessions and buildTunnels, arriving by a different route.
	if len(prior.Window) != 2 || len(prior.History) != 1 {
		t.Errorf("the prior was mutated: window=%d history=%d, want 2 and 1",
			len(prior.Window), len(prior.History))
	}
	// AND ITS CONTENTS, not just its length. An append into spare capacity
	// leaves the length alone and overwrites the element past it, so a
	// length-only check misses precisely the case this exists for.
	full := prior.Window[:cap(prior.Window)]
	for i := range priorWin {
		if full[i] != priorWin[i] {
			t.Errorf("the prior's window contents changed at %d", i)
		}
	}
	if len(full) > 2 && full[2] {
		t.Error("the fold appended into the prior's spare capacity — the caller's " +
			"state was written through, which is the impurity this extraction " +
			"exists to remove")
	}
	if len(next.Window) != 3 || len(next.History) != 2 {
		t.Errorf("next window=%d history=%d, want 3 and 2", len(next.Window), len(next.History))
	}
}

// TestFoldPingSuppressesAnUnchangedResult, and says so through its third return
// rather than by handing back nil — which is what let the collector keep `last`
// current while emitting nothing.
func TestFoldPingSuppressesAnUnchangedResult(t *testing.T) {
	row := routeros.Reply{"time": "10ms"}
	p1, s1, changed1 := FoldPing(PingFold{}, "1.1.1.1", 5000, row, 100)
	if !changed1 {
		t.Fatal("the first result was suppressed")
	}
	p2, _, changed2 := FoldPing(s1, "1.1.1.1", 5000, row, 200)
	if changed2 {
		t.Error("an identical reading was reported as changed; every result would " +
			"wake every subscribed browser")
	}
	// AND THE PAYLOAD IS STILL BUILT. Suppression is about whether to SEND, not
	// about whether the series advanced — `Last()` must stay current or a page
	// opening mid-silence replays a stale reading.
	if p2 == nil || p2.TS != 200 {
		t.Errorf("payload = %+v; a suppressed result must still produce a current "+
			"payload for replay", p2)
	}
	if p1.TS != 100 {
		t.Errorf("the first payload's ts changed to %d", p1.TS)
	}
}

// TestFoldPingBoundsBothRings. Unbounded growth in a fold is invisible until a
// session has been up for days — the history is per-router and the window feeds
// every loss percentage.
func TestFoldPingBoundsBothRings(t *testing.T) {
	state := PingFold{}
	for i := 0; i < pingMaxHistory+pingLossWindow+50; i++ {
		_, state, _ = FoldPing(state, "1.1.1.1", 5000, routeros.Reply{"time": "1ms"}, int64(i))
	}
	if len(state.Window) != pingLossWindow {
		t.Errorf("window = %d, want %d", len(state.Window), pingLossWindow)
	}
	if len(state.History) != pingMaxHistory {
		t.Errorf("history = %d, want %d", len(state.History), pingMaxHistory)
	}
}

// TestFoldPingLossIsOverTheWindowNotAllTime. A router that dropped packets an
// hour ago and is fine now must read 0%, not carry the outage for ever.
func TestFoldPingLossIsOverTheWindowNotAllTime(t *testing.T) {
	state := PingFold{}
	// One timeout, then a full window of replies.
	_, state, _ = FoldPing(state, "t", 5000, routeros.Reply{"status": "timeout"}, 0)
	for i := 0; i < pingLossWindow; i++ {
		var pl *PingPayload
		pl, state, _ = FoldPing(state, "t", 5000, routeros.Reply{"time": "1ms"}, int64(i+1))
		if i == pingLossWindow-1 && (pl.Loss == nil || *pl.Loss != 0) {
			t.Errorf("loss = %v after a full window of replies; the old timeout is "+
				"still being counted", pl.Loss)
		}
	}
}
