package store

// What the browser is allowed to see of the settings.
//
// TWO DIFFERENT BOUNDARIES, and conflating them is how a leak happens.
//
// `Public` is for an administrator: everything, with the six credential fields
// MASKED. The mask distinguishes set from unset — a bullet string when a value
// is configured, an empty string when it is not — so the page can show
// "configured" without receiving the secret.
//
// `ViewerPublic` is for everyone else: a NAMED SUBSET and nothing more. It is an
// ALLOW-LIST, and that is the load-bearing property. Starting from the whole
// object and deleting the sensitive keys would leak every setting added after
// the code was written, which is precisely the failure an allow-list cannot
// have.
//
// `testdata/settings-public-cases.json` is generated by running the LIVE
// `src/settings.js` against a synthetic /data, so these lists are pinned to the
// original rather than to a reading of it.

// CredentialFields are never sent, only their masked presence.
var CredentialFields = []string{
	"routerPass", "telegramBotToken", "pushbulletApiKey",
	"smtpUser", "smtpPass", "ntfyToken",
}

// Mask is the sentinel the browser receives in place of a configured credential.
// Eight bullets; the page tests for this exact string to decide whether a field
// is already set, so its length is part of the contract rather than decoration.
const Mask = "••••••••"

// ViewerFields is what a non-administrator may read.
//
// ── `authMode` IS IN THE LIST, AND THE LIVE COMMENT IS MISLEADING ──────────
//
// That comment says the subset "excludes router connection details, auth config,
// and notification-channel targets". `authMode` is auth config by any reading,
// and it is in the list anyway — the browser needs it to know whether to offer a
// login form at all. A port written from the COMMENT rather than from the LIST
// would drop it and break the login page for exactly the users this subset is
// for. Copied from the list.
var ViewerFields = []string{
	"authMode",
	"pingEnabled", "pingTarget",
	"topN", "topTalkersN", "firewallTopN", "vpnDashTopN", "maxConns", "historyMinutes",
	"alertCpuThreshold", "alertPingLoss",
	"activeRouterId",
	"pageWifi", "pageWireless", "pageInterfaces", "pageDhcp", "pageVpn", "pageConnections",
	"pageFirewall", "pageLogs", "pageBandwidth", "pageRouting", "pageTopology",
	"pageVlans", "pagePpp", "pageBridges", "pageDns", "pageCapsman", "pagePackages",
	"pageRosusers", "pageQueues", "pageWan", "pageDevices", "pageAudit", "pageBackups",
	"displayTimezone",
	// Whether the My Alerts tab exists at all. A non-admin is the whole audience
	// for that tab and only ever sees this subset, so leaving it out would hide
	// the feature from exactly the people it is for. A feature flag, not
	// configuration — it discloses nothing.
	"userNotifyEnabled",
}

// Public is the administrator's view: a copy with credentials masked.
//
// THE INPUT MUST ALREADY BE MERGED over the defaults and the environment. The
// original's `getPublic` calls `load()`, which does that merge; this takes the
// merged map so the disclosure rule stays separate from where the values came
// from. `Store.Settings()` reads the FILE ONLY and is therefore not that map, so
// passing its result here would disclose an unmerged view.
func (s Settings) Public() Settings {
	out := make(Settings, len(s))
	for k, v := range s {
		out[k] = v
	}
	for _, f := range CredentialFields {
		// `s[f] ? MASK : ''` — the original's truthiness, which for these
		// fields means a non-empty string. A missing key and an empty value are
		// the same thing here, and both must yield the empty string rather than
		// the mask: a page showing "configured" for a credential nobody set
		// sends an operator looking for a value that is not there.
		if str, ok := v(s[f]); ok && str != "" {
			out[f] = Mask
		} else {
			out[f] = ""
		}
	}
	return out
}

// ViewerPublic is the non-administrator's view: the allow-list, nothing else.
//
// A field absent from the merged settings is written as nil, exactly as the
// original writes `undefined` — the key is present with no value, which is what
// the browser distinguishes from the key being missing entirely.
func (s Settings) ViewerPublic() Settings {
	out := make(Settings, len(ViewerFields))
	for _, f := range ViewerFields {
		out[f] = s[f]
	}
	return out
}

// v reports a value as a string when it is one. Anything else is not a
// credential this code put there, and is treated as absent rather than
// stringified — `fmt.Sprint` on a number would produce a non-empty string and
// mask a field that holds no secret.
func v(x any) (string, bool) {
	s, ok := x.(string)
	return s, ok
}
