package store

// `UpdateIdentity` against the LIVE `Routers.updateIdentity`, executed.
//
// The corpus is generated by the identity-fields corpus, which requires
// the live module against a throwaway DATA_DIR, seeds a routers.json, calls the
// real function and reads back what landed on disk. So what is compared here is
// not a reading of the rule — it is the rule's own output.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type identityCase struct {
	Why      string `json:"why"`
	Identity *struct {
		Model     any `json:"model"`
		Serial    any `json:"serial"`
		OSVersion any `json:"osVersion"`
	} `json:"identity"`
	Base      map[string]any `json:"base"`
	Wrote     bool           `json:"wrote"`
	Model     *string        `json:"model"`
	Serial    *string        `json:"serial"`
	OSVersion *string        `json:"osVersion"`
}

// asReported is rule 1 applied at the BOUNDARY rather than inside the function.
//
// The live rule is `typeof val !== 'string'` — a number, a boolean, an object or
// null is skipped. In Go the hook's argument is a `collect.SystemPayload`, whose
// fields are already `string`, so a non-string cannot arrive: the type system
// enforces what JavaScript checks at runtime. What the corpus's non-string cases
// therefore pin is that such a value reaches `UpdateIdentity` as the EMPTY
// STRING and is skipped by rule 2 — which is the same observable outcome and the
// only one reachable from Go.
func asReported(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	return ""
}

func TestUpdateIdentityMatchesTheLiveFunction(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "..", "testdata", "identity-cases.json"))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var corpus struct {
		Base  map[string]any `json:"base"`
		Cases []identityCase `json:"cases"`
	}
	if err := json.Unmarshal(raw, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(corpus.Cases) == 0 {
		t.Fatal("the corpus is empty")
	}
	wrote := 0
	for _, c := range corpus.Cases {
		if c.Wrote {
			wrote++
		}
	}
	// A corpus in which nothing writes would pass a function that never writes.
	if wrote == 0 || wrote == len(corpus.Cases) {
		t.Fatalf("the corpus does not separate writing from not writing: %d of %d write",
			wrote, len(corpus.Cases))
	}

	for _, c := range corpus.Cases {
		t.Run(c.Why, func(t *testing.T) {
			dir := t.TempDir()
			base := c.Base
			if base == nil {
				base = corpus.Base
			}
			seed, err := json.MarshalIndent([]any{base}, "", "  ")
			if err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(dir, "routers.json"), seed, 0o600); err != nil {
				t.Fatal(err)
			}
			s := &Store{Dir: dir}

			var ident Identity
			if c.Identity != nil {
				ident = Identity{
					Model:     asReported(c.Identity.Model),
					Serial:    asReported(c.Identity.Serial),
					OSVersion: asReported(c.Identity.OSVersion),
				}
			}

			got, err := s.UpdateIdentity("rtr-1", ident)
			if err != nil {
				t.Fatalf("UpdateIdentity: %v", err)
			}
			if got != c.Wrote {
				t.Errorf("wrote = %v, live wrote = %v", got, c.Wrote)
			}

			after, err := os.ReadFile(filepath.Join(dir, "routers.json"))
			if err != nil {
				t.Fatal(err)
			}
			var recs []map[string]any
			if err := json.Unmarshal(after, &recs); err != nil {
				t.Fatalf("the record is no longer parseable: %v", err)
			}
			if len(recs) != 1 {
				t.Fatalf("the file holds %d records, want 1", len(recs))
			}
			for field, want := range map[string]*string{
				"model": c.Model, "serial": c.Serial, "osVersion": c.OSVersion,
			} {
				var have *string
				if v, ok := recs[0][field].(string); ok {
					have = &v
				}
				switch {
				case want == nil && have != nil:
					t.Errorf("%s = %q on disk; the live function left it absent", field, *have)
				case want != nil && have == nil:
					t.Errorf("%s is absent on disk; the live function left %q", field, *want)
				case want != nil && have != nil && *want != *have:
					t.Errorf("%s = %q, live = %q", field, *have, *want)
				}
			}
		})
	}
}

// TestUpdateIdentityLeavesEverythingElseAlone.
//
// The corpus compares the three identity fields, which is exactly what it can
// see. What it CANNOT see is the rest of the record — and that is the failure
// mode this port has hit twice already (`users_public.go`, `routers_public.go`):
// a writer that decodes into a struct it did not define rewrites the parts of
// the document it does not know about. A background poll silently dropping a
// router's `collection` block or its `backup` schedule would be the worst
// possible version of it, because it happens unprompted and repeatedly.
func TestUpdateIdentityLeavesEverythingElseAlone(t *testing.T) {
	dir := t.TempDir()
	// Deliberately carries keys no Go struct in this package declares.
	seed := `[{"id":"rtr-1","label":"One","host":"198.51.100.1","port":8728,
	  "username":"api","password":"","model":"old","serial":"S1","osVersion":"7.23",
	  "collection":{"mode":"poll","off":["dns"]},
	  "backup":{"schedule":"daily","keepCount":7},
	  "geo":{"auto":{"ip":"203.0.113.9","city":"Nowhere"}},
	  "somethingNobodyModels":{"deep":[1,2,3]}}]`
	if err := os.WriteFile(filepath.Join(dir, "routers.json"), []byte(seed), 0o600); err != nil {
		t.Fatal(err)
	}
	s := &Store{Dir: dir}
	if _, err := s.UpdateIdentity("rtr-1", Identity{Model: "new", OSVersion: "7.24"}); err != nil {
		t.Fatalf("UpdateIdentity: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(dir, "routers.json"))
	if err != nil {
		t.Fatal(err)
	}
	var recs []map[string]any
	if err := json.Unmarshal(raw, &recs); err != nil {
		t.Fatal(err)
	}
	r := recs[0]
	if r["model"] != "new" || r["osVersion"] != "7.24" {
		t.Fatalf("the identity did not land: model=%v osVersion=%v", r["model"], r["osVersion"])
	}
	if r["serial"] != "S1" {
		t.Errorf("serial = %v; an unreported field must survive, not be cleared", r["serial"])
	}
	for _, key := range []string{"collection", "backup", "geo", "somethingNobodyModels"} {
		if _, ok := r[key]; !ok {
			t.Errorf("%q was dropped by an identity write. A background poll that quietly loses "+
				"a router's collection config or backup schedule is the worst version of this "+
				"failure: unprompted, repeated, and invisible until the operator looks.", key)
		}
	}
}

// TestUnknownRouterIsNotAnError.
//
// A router deleted while its background session was mid-poll is ordinary. The
// live function returns null for it; an error here would be logged once per poll
// forever.
func TestUnknownRouterIsNotAnError(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "routers.json"), []byte(`[]`), 0o600); err != nil {
		t.Fatal(err)
	}
	s := &Store{Dir: dir}
	wrote, err := s.UpdateIdentity("gone", Identity{Model: "x"})
	if err != nil {
		t.Errorf("a deleted router reported an error: %v", err)
	}
	if wrote {
		t.Error("wrote for a router that does not exist")
	}
}
