package store

// `UpdateUser` and `DeleteUser` against the LIVE `Users.updateUser` and
// `Users.deleteUser`, executed.
//
// The corpus is generated by the userwrite corpus, which requires the live
// module against a throwaway DATA_DIR, seeds a users.json, calls the real
// functions and reads back what landed on disk. What is compared is not a
// reading of the rules — it is the rules' own output.
//
// The salt is 32 random bytes, so the hash differs on every run and cannot be a
// corpus value. What the corpus records instead is STRUCTURAL — whether salt and
// passwordHash CHANGED — which is exactly the property the password guard turns
// on, and the only one that could be compared at all.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type userUpdateCase struct {
	Why string `json:"why"`
	ID  string `json:"id"`
	// A MAP, not a struct, because JSON `null` and an ABSENT KEY are different
	// things here and a struct field collapses them into one nil.
	//
	// That is not a detail of the harness — it is the live rule. `updates.role
	// !== undefined` is TRUE for an explicit null, so `{"role": null}` reaches
	// `_validRole` and THROWS, while `{}` leaves the role alone. A Go struct
	// decoding both to nil passed twenty-one cases and failed exactly the one
	// that separates them, which is how this was found.
	//
	// The HTTP layer faces the same distinction for the same reason: a body of
	// `{"role": null}` must be a 400 and a body of `{}` must be a no-op.
	Patch            map[string]any `json:"patch"`
	Threw            *string        `json:"threw"`
	ReturnedNull     bool           `json:"returnedNull"`
	ReturnedKeys     []string       `json:"returnedKeys"`
	Username         *string        `json:"username"`
	Role             *string        `json:"role"`
	AllowedRouterIDs []string       `json:"allowedRouterIds"`
	CreatedAt        *int64         `json:"createdAt"`
	SaltChanged      bool           `json:"saltChanged"`
	HashChanged      bool           `json:"hashChanged"`
	OtherIntact      bool           `json:"otherIntact"`
	Count            int            `json:"count"`
}

type userDeleteCase struct {
	Why       string   `json:"why"`
	ID        string   `json:"id"`
	Removed   bool     `json:"removed"`
	Count     int      `json:"count"`
	Remaining []string `json:"remaining"`
	IsArray   bool     `json:"isArray"`
}

func loadUserWriteCorpus(t *testing.T) struct {
	Seed    []map[string]any `json:"seed"`
	Updates []userUpdateCase `json:"updates"`
	Deletes []userDeleteCase `json:"deletes"`
} {
	t.Helper()
	var out struct {
		Seed    []map[string]any `json:"seed"`
		Updates []userUpdateCase `json:"updates"`
		Deletes []userDeleteCase `json:"deletes"`
	}
	raw, err := os.ReadFile(filepath.Join("..", "..", "testdata", "userwrite-cases.json"))
	if err != nil {
		t.Fatalf("no corpus — run: node tools/userwrite-cases.js: %v", err)
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(out.Updates) == 0 || len(out.Deletes) == 0 {
		t.Fatal("the corpus is empty")
	}
	return out
}

func seedUsers(t *testing.T, seed []map[string]any) (string, *Store) {
	t.Helper()
	dir := t.TempDir()
	b, err := json.MarshalIndent(seed, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "users.json"), b, 0o600); err != nil {
		t.Fatal(err)
	}
	return dir, &Store{Dir: dir}
}

// patchFrom turns the corpus's JSON patch into `UserUpdates`.
//
// ── THE ARRAY GUARD IS APPLIED HERE, AND THAT IS WHERE IT BELONGS ──────────
//
// The live rule is `Array.isArray(updates.allowedRouterIds)`: a string, a number
// or null is IGNORED. In Go the pointer already carries "absent", so a non-array
// must decode to a NIL pointer rather than to an error or a one-element list.
// That translation is the HTTP layer's job in the real app, and this mirrors it
// so the corpus's three non-array cases test the same thing here that they will
// test there.
func patchFrom(c userUpdateCase) UserUpdates {
	var up UserUpdates

	if v, present := c.Patch["username"]; present {
		// `String(updates.username)` — the live call stringifies whatever it is
		// given, and the corpus carries a numeric username for exactly that.
		s := patchString(v)
		up.Username = &s
	}
	// PRESENT, not non-nil. See the type's comment: an explicit null throws and
	// an absent key does not.
	if v, present := c.Patch["role"]; present {
		s := patchString(v)
		up.Role = &s
	}
	// THE ARRAY GUARD, applied here because that is where the live rule applies
	// it: `Array.isArray(...)`, not `!== undefined`. A string, a number or null
	// is IGNORED — so it must decode to a NIL pointer rather than to an error or
	// a one-element list. The real HTTP layer does the same translation, and the
	// corpus's three non-array cases test the same thing in both places.
	if arr, ok := c.Patch["allowedRouterIds"].([]any); ok {
		ids := make([]string, 0, len(arr))
		for _, v := range arr {
			if s, ok := v.(string); ok {
				ids = append(ids, s)
			}
		}
		up.AllowedRouterIDs = &ids
	}
	if v, present := c.Patch["password"]; present {
		s := patchString(v)
		up.Password = &s
	}
	return up
}

// patchString is `String(v)` for the shapes this corpus carries.
//
// NOT the package's own `jsString` (routeradd.go), which maps nil to "" — that
// is right for a router record, where an absent key means no value. Here an
// explicit `null` is a VALUE that was sent, and `String(null)` is the four
// characters "null", which `_validRole` rejects. Rejecting it is the behaviour
// under test, so mapping it to "" would test the wrong thing while still
// failing — which is the worst of both.
func patchString(v any) string {
	switch t := v.(type) {
	case string:
		return t
	case nil:
		return "null"
	case float64:
		b, _ := json.Marshal(t)
		return string(b)
	default:
		b, _ := json.Marshal(t)
		return string(b)
	}
}

func TestUpdateUserMatchesTheLiveFunction(t *testing.T) {
	corpus := loadUserWriteCorpus(t)

	threw, rehashed := 0, 0
	for _, c := range corpus.Updates {
		if c.Threw != nil {
			threw++
		}
		if c.HashChanged {
			rehashed++
		}
	}
	// A corpus where nothing throws would pass a port with no validation, and one
	// where everything re-hashes would pass a port that ignores the empty-password
	// guard. Both are the failures this file exists for.
	if threw == 0 {
		t.Fatal("no case throws; the role validation is untested")
	}
	if rehashed == 0 || rehashed == len(corpus.Updates) {
		t.Fatalf("%d of %d cases re-hash; the corpus does not separate the two branches",
			rehashed, len(corpus.Updates))
	}

	for _, c := range corpus.Updates {
		t.Run(c.Why, func(t *testing.T) {
			dir, s := seedUsers(t, corpus.Seed)
			before := readUserRecord(t, dir, c.ID)

			pub, err := s.UpdateUser(c.ID, patchFrom(c))

			switch {
			case c.Threw != nil:
				if err == nil {
					t.Fatalf("the live function threw (%s) and this returned no error", *c.Threw)
				}
			case c.ReturnedNull:
				if !isNoSuchUser(err) {
					t.Fatalf("the live function answered null for an unknown id; got err=%v", err)
				}
				return
			default:
				if err != nil {
					t.Fatalf("UpdateUser: %v", err)
				}
			}

			after := readUserRecord(t, dir, c.ID)

			// WHEN THE LIVE FUNCTION THREW, NOTHING MAY HAVE MOVED. A port that
			// validated after writing would pass every other assertion here.
			if c.Threw != nil {
				if !sameRecord(before, after) {
					t.Errorf("the role was refused and the record still changed:\n  before %v\n  after  %v",
						before, after)
				}
				return
			}

			if c.Username != nil && after["username"] != *c.Username {
				t.Errorf("username = %v, live = %q", after["username"], *c.Username)
			}
			if c.Role != nil && after["role"] != *c.Role {
				t.Errorf("role = %v, live = %q", after["role"], *c.Role)
			}
			if got := stringsOf(after["allowedRouterIds"]); !sameStrings(got, c.AllowedRouterIDs) {
				t.Errorf("allowedRouterIds = %v, live = %v", got, c.AllowedRouterIDs)
			}
			// `createdAt` is not in the update path at all.
			if c.CreatedAt != nil {
				if got, ok := after["createdAt"].(float64); !ok || int64(got) != *c.CreatedAt {
					t.Errorf("createdAt = %v, live = %d — it is not in the update path, so a port "+
						"that moved it is rebuilding the record rather than patching it",
						after["createdAt"], *c.CreatedAt)
				}
			}

			// THE STRUCTURAL HALF. This is the empty-password guard.
			if got := before["salt"] != after["salt"]; got != c.SaltChanged {
				t.Errorf("saltChanged = %v, live = %v", got, c.SaltChanged)
			}
			if got := before["passwordHash"] != after["passwordHash"]; got != c.HashChanged {
				t.Errorf("hashChanged = %v, live = %v. An empty password must LEAVE THE CREDENTIAL "+
					"ALONE — the edit form submits one on every save where nobody typed a new "+
					"password, so getting this wrong locks the account out on a rename.",
					got, c.HashChanged)
			}

			// THE PUBLIC VIEW must not carry the credential.
			for _, secret := range []string{"salt", "passwordHash"} {
				if _, leaked := pub[secret]; leaked {
					t.Errorf("UpdateUser returned %q to its caller", secret)
				}
			}
			for _, keep := range c.ReturnedKeys {
				if _, ok := pub[keep]; !ok {
					t.Errorf("the public view lost %q, which the live one returns", keep)
				}
			}

			// THE NEIGHBOUR is untouched, byte for byte.
			if c.OtherIntact {
				other := "u-2"
				if c.ID == "u-2" {
					other = "u-1"
				}
				want, _ := json.Marshal(findSeed(corpus.Seed, other))
				got, _ := json.Marshal(readUserRecord(t, dir, other))
				if string(want) != string(got) {
					t.Errorf("the OTHER user's record was rewritten:\n  want %s\n  got  %s", want, got)
				}
			}
		})
	}
}

func TestDeleteUserMatchesTheLiveFunction(t *testing.T) {
	corpus := loadUserWriteCorpus(t)
	removed := 0
	for _, c := range corpus.Deletes {
		if c.Removed {
			removed++
		}
	}
	if removed == 0 || removed == len(corpus.Deletes) {
		t.Fatalf("%d of %d deletes succeed; the corpus does not separate found from not-found",
			removed, len(corpus.Deletes))
	}

	for _, c := range corpus.Deletes {
		t.Run(c.Why, func(t *testing.T) {
			dir, s := seedUsers(t, corpus.Seed)
			got, err := s.DeleteUser(c.ID)
			if err != nil {
				t.Fatalf("DeleteUser: %v", err)
			}
			if got != c.Removed {
				t.Errorf("removed = %v, live = %v", got, c.Removed)
			}

			raw, err := os.ReadFile(filepath.Join(dir, "users.json"))
			if err != nil {
				t.Fatal(err)
			}
			// A BARE ARRAY. `internal/store`'s header calls this a security
			// property: a wrapper makes a rolled-back binary read ZERO users,
			// which re-opens the unauthenticated setup route.
			var records []map[string]any
			if err := json.Unmarshal(raw, &records); err != nil {
				t.Fatalf("users.json is no longer a bare array: %v", err)
			}
			if len(records) != c.Count {
				t.Errorf("%d records left, live left %d", len(records), c.Count)
			}
			ids := make([]string, 0, len(records))
			for _, r := range records {
				id, _ := r["id"].(string)
				ids = append(ids, id)
			}
			if !sameStrings(ids, c.Remaining) {
				t.Errorf("remaining = %v, live = %v", ids, c.Remaining)
			}
		})
	}
}

// TestUpdateUserLeavesTheOTHER_RecordsByteIdentical.
//
// ── THE CORPUS CANNOT SEE THIS, AND A MUTATION RUN PROVED IT ───────────────
//
// The corpus records `otherIntact` by comparing the neighbour's record against
// the seed — but both sides go through `json.Marshal` of a map, which SORTS
// KEYS. So a port that decoded the whole file into maps and re-encoded it looked
// identical, and the mutation that does exactly that SURVIVED eleven other
// checks on 2026-08-28.
//
// It matters for the reason `users_write.go`'s header sets out: Go sorts map
// keys and JavaScript does not, so one rename would rewrite every user's field
// order and turn a one-field edit into a maximal diff on the one file nobody
// wants to have to eyeball. Harmless to the app, which parses it; not harmless
// to whoever has to review it.
func TestUpdateUserLeavesTheOtherRecordsByteIdentical(t *testing.T) {
	dir := t.TempDir()
	// A DELIBERATELY unsorted key order, so a re-encode is visible.
	seed := `[
  {"username":"alice","id":"u-1","role":"admin","salt":"aa","passwordHash":"bb",
   "allowedRouterIds":[],"createdAt":1700000000000},
  {"username":"bob","id":"u-2","role":"viewer","salt":"cc","passwordHash":"dd",
   "allowedRouterIds":["rtr-1"],"createdAt":1700000001000}
]`
	if err := os.WriteFile(filepath.Join(dir, "users.json"), []byte(seed), 0o600); err != nil {
		t.Fatal(err)
	}
	s := &Store{Dir: dir}
	name := "alice-renamed"
	if _, err := s.UpdateUser("u-1", UserUpdates{Username: &name}); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, "users.json"))
	if err != nil {
		t.Fatal(err)
	}
	if got := string(raw); !containsInOrder(got, `"username": "bob"`, `"id": "u-2"`) {
		t.Errorf("the UNTOUCHED record was re-encoded — its keys are no longer in the order it "+
			"was written in. Editing one user must not rewrite everybody else's record.\n%s", got)
	}
}

// TestDeleteUserLeavesTheSurvivorsBYTE-IDENTICAL.
//
// The corpus can see which ids are left; it cannot see whether the records that
// stayed were re-encoded. They must not be — `users_write.go`'s header records
// why: Go sorts map keys, so a decode-and-re-encode rewrites every survivor's
// field order and turns one deletion into a maximal diff on the one file nobody
// wants to have to eyeball.
func TestDeleteUserLeavesTheSurvivorsUntouched(t *testing.T) {
	corpus := loadUserWriteCorpus(t)
	dir := t.TempDir()
	// Written with a DELIBERATELY unsorted key order, so a re-encode is visible.
	seed := `[
  {"username":"alice","id":"u-1","role":"admin","salt":"aa","passwordHash":"bb",
   "allowedRouterIds":[],"createdAt":1700000000000},
  {"username":"bob","id":"u-2","role":"viewer","salt":"cc","passwordHash":"dd",
   "allowedRouterIds":["rtr-1"],"createdAt":1700000001000}
]`
	if err := os.WriteFile(filepath.Join(dir, "users.json"), []byte(seed), 0o600); err != nil {
		t.Fatal(err)
	}
	s := &Store{Dir: dir}
	if _, err := s.DeleteUser("u-1"); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, "users.json"))
	if err != nil {
		t.Fatal(err)
	}
	// `username` BEFORE `id` is the order the seed used and JSON marshalling of a
	// map would not preserve.
	if got := string(raw); !containsInOrder(got, `"username": "bob"`, `"id": "u-2"`) {
		t.Errorf("the surviving record was re-encoded — its keys are no longer in the order it "+
			"was written in. One deletion should not rewrite everybody else's record.\n%s", got)
	}
	_ = corpus
}

// ---- small helpers ---------------------------------------------------------

func readUserRecord(t *testing.T, dir, id string) map[string]any {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(dir, "users.json"))
	if err != nil {
		t.Fatal(err)
	}
	var records []map[string]any
	if err := json.Unmarshal(raw, &records); err != nil {
		t.Fatal(err)
	}
	for _, r := range records {
		if r["id"] == id {
			return r
		}
	}
	return nil
}

func findSeed(seed []map[string]any, id string) map[string]any {
	for _, r := range seed {
		if r["id"] == id {
			return r
		}
	}
	return nil
}

func sameRecord(a, b map[string]any) bool {
	x, _ := json.Marshal(a)
	y, _ := json.Marshal(b)
	return string(x) == string(y)
}

func stringsOf(v any) []string {
	arr, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(arr))
	for _, x := range arr {
		s, _ := x.(string)
		out = append(out, s)
	}
	return out
}

func sameStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func isNoSuchUser(err error) bool { return err == ErrNoSuchUser }

func containsInOrder(s string, parts ...string) bool {
	at := 0
	for _, p := range parts {
		i := indexFrom(s, p, at)
		if i < 0 {
			return false
		}
		at = i + len(p)
	}
	return true
}

func indexFrom(s, sub string, from int) int {
	if from > len(s) {
		return -1
	}
	for i := from; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}
