// pagesgen writes the TypeScript view of `internal/pages`.
//
// ── WHY IT IS NOT PART OF cmd/tsgen ─────────────────────────────────────────
//
// `tsgen` answers one question — what shape does this Go struct take on the
// wire — and its whole header is about json tags, omitempty and custom
// marshallers. This exports a small value table and needs none of that: it
// IMPORTS `internal/pages` and reads the slice, where tsgen has to parse an AST
// because its subject is scattered across a package it cannot link.
//
// Two small generators that each say what they do beat one that needs a
// paragraph to explain which half you are looking at.
//
// ── WHAT IT REMOVES ─────────────────────────────────────────────────────────
//
// `PORTED` and `PAGE_TITLES` were hand-written in web/src/main.ts, which made
// them two of the five places the same 26 page keys were spelled out. They are
// generated now, so a page added in Go appears in the TypeScript or the build
// goes red -- `-check` runs in tools/verify.sh.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"mikrodash/internal/pages"
)

const outRel = "web/src/gen/pages.ts"

func main() {
	out := flag.String("out", outRel, "file to write")
	check := flag.Bool("check", false, "fail if the committed file is stale instead of writing it")
	flag.Parse()

	body := render()

	if *check {
		have, err := os.ReadFile(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "pagesgen: %s is missing; run `go run ./cmd/pagesgen`\n", *out)
			os.Exit(1)
		}
		if !bytes.Equal(bytes.TrimSpace(have), bytes.TrimSpace(body)) {
			fmt.Fprintf(os.Stderr, "pagesgen: %s is STALE — the page list changed and the "+
				"TypeScript was not regenerated.\nRun: go run ./cmd/pagesgen\n", *out)
			os.Exit(1)
		}
		fmt.Printf("pagesgen: %s is current (%d pages)\n", *out, len(pages.All))
		return
	}

	if err := os.WriteFile(*out, body, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "pagesgen:", err)
		os.Exit(1)
	}
	fmt.Printf("pagesgen: wrote %s — %d pages\n", *out, len(pages.All))
}

func render() []byte {
	var b strings.Builder
	b.WriteString(`// GENERATED by cmd/pagesgen — do not edit.
//
// The app's pages, from internal/pages. That package is the source for all three
// consumers: this file, the markup cmd/webbuild composes, and the URL
// internal/server registers per page.
//
// A KEY IS THREE THINGS AT ONCE — the URL path (` + "`/logs`" + `), the id of its markup
// (` + "`#page-logs`" + `) and the room collectors emit to (` + "`page-logs`" + `). One name per
// page, nothing to map. It also means renaming one is a protocol change.

export interface Page {
  /** URL path, markup id and room name. */
  key: string;
  /** Header text. Empty where the key already reads correctly on its own. */
  title: string;
  /** URL segment. Equal to the key for all but the dashboard, served at /home. */
  path: string;
}

export const PAGES: readonly Page[] = [
`)
	for _, p := range pages.All {
		fmt.Fprintf(&b, "  { key: %s, title: %s, path: %s },\n",
			strconv.Quote(p.Key), strconv.Quote(p.Title), strconv.Quote(p.URL()))
	}
	b.WriteString(`];

/** Every page key, in nav order. */
export const PAGE_KEY_SET: ReadonlySet<string> = new Set(PAGES.map((p) => p.key));

/** Header text for a key. Falls back to the key, which is deliberate: a page
 *  whose key already reads correctly needs no second spelling of it. */
export function pageTitle(key: string): string {
  return PAGES.find((p) => p.key === key)?.title || key;
}

/** The URL path for a page key, with its leading slash. */
export function pagePath(key: string): string {
  return '/' + (PAGES.find((p) => p.key === key)?.path || key);
}

/** The page key served at a URL segment, or '' when nothing matches. */
export function pageForPath(pathname: string): string {
  const seg = pathname.replace(/^\/+/, '').replace(/\/.*$/, '');
  return PAGES.find((p) => p.path === seg)?.key || '';
}
`)
	return []byte(b.String())
}
